/*
 * Settings for RepositoryPattern
 * Generated by CodeNodeIO ModuleSaveService
 * License: Apache 2.0
 */

pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "RepositoryPattern"
