/*
 * RepositoryPatternViewModel
 * Generated by CodeNodeIO RuntimeViewModelGenerator
 * License: Apache 2.0
 */

package io.codenode.repositorypattern

import androidx.lifecycle.ViewModel
import io.codenode.fbpdsl.model.ExecutionState
import io.codenode.fbpdsl.model.FlowGraph
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import io.codenode.repositorypattern.generated.RepositoryPatternControllerInterface

// ===== MODULE PROPERTIES START =====
// Auto-generated from sink node input ports. Do not edit this section manually.
// Changes here will be overwritten on next code generation.

object RepositoryPatternState {

    internal val _filteredList = MutableStateFlow(null)
    val filteredListFlow: StateFlow<Any> = _filteredList.asStateFlow()

    fun reset() {
        _filteredList.value = null
    }
}

// ===== MODULE PROPERTIES END =====

// ============================================================
// ViewModel
// Binding interface between composable UI and FlowGraph.
// User-editable section below — preserved across regenerations.
// ============================================================

/**
 * ViewModel for the RepositoryPattern composable.
 * Bridges FlowGraph domain logic with Compose UI.
 *
 * @param controller The RepositoryPatternControllerInterface that manages FlowGraph execution
 * @generated by CodeNodeIO RuntimeViewModelGenerator
 */
class RepositoryPatternViewModel(
    private val controller: RepositoryPatternControllerInterface
) : ViewModel() {

    // Observable state from module properties
    val filteredList: StateFlow<Any> = RepositoryPatternState.filteredListFlow

    // Execution state from controller
    val executionState: StateFlow<ExecutionState> = controller.executionState

    // Control methods
    fun start(): FlowGraph = controller.start()

    fun stop(): FlowGraph = controller.stop()

    fun reset(): FlowGraph = controller.reset()

    fun pause(): FlowGraph = controller.pause()

    fun resume(): FlowGraph = controller.resume()
}

