/*
 * EntityDisplayCodeNodeGenerator - Generates {PluralName}DisplayCodeNode.kt implementing CodeNodeDefinition
 * License: Apache 2.0
 */

package io.codenode.flowgraphgenerate.generator

/**
 * Generates a {PluralName}DisplayCodeNode.kt file implementing CodeNodeDefinition.
 * This is a SINK node with 2 String inputs (result, error) that updates
 * the module's State object.
 *
 * Replaces the legacy EntityDisplayGenerator which produced factory functions.
 */
class EntityDisplayCodeNodeGenerator {

    fun generate(spec: EntityModuleSpec): String {
        val pluralName = spec.pluralName
        val nodesPackage = "${spec.basePackage}.nodes"

        return buildString {
            appendLine("/*")
            appendLine(" * ${pluralName}DisplayCodeNode - Self-contained sink node for display output")
            appendLine(" * Generated by CodeNodeIO EntityDisplayCodeNodeGenerator")
            appendLine(" * License: Apache 2.0")
            appendLine(" */")
            appendLine()
            appendLine("package $nodesPackage")
            appendLine()
            appendLine("import io.codenode.fbpdsl.model.CodeNodeFactory")
            appendLine("import io.codenode.fbpdsl.runtime.CodeNodeDefinition")
            appendLine("import io.codenode.fbpdsl.model.CodeNodeType")
            appendLine("import io.codenode.fbpdsl.runtime.NodeRuntime")
            appendLine("import io.codenode.fbpdsl.runtime.PortSpec")
            appendLine("import ${spec.basePackage}.${pluralName}State")
            appendLine()
            appendLine("/**")
            appendLine(" * Sink node that receives result and error values and updates ${pluralName}State.")
            appendLine(" *")
            appendLine(" * Uses SinkIn2 (synchronous receive from both channels).")
            appendLine(" */")
            appendLine("object ${pluralName}DisplayCodeNode : CodeNodeDefinition {")
            appendLine("    override val name = \"${pluralName}Display\"")
            appendLine("    override val category = CodeNodeType.SINK")
            appendLine("    override val description = \"Displays result and error messages for ${pluralName.lowercase()} operations\"")
            appendLine("    override val inputPorts = listOf(")
            appendLine("        PortSpec(\"result\", String::class),")
            appendLine("        PortSpec(\"error\", String::class)")
            appendLine("    )")
            appendLine("    override val outputPorts = emptyList<PortSpec>()")
            appendLine()
            appendLine("    override fun createRuntime(name: String): NodeRuntime {")
            appendLine("        return CodeNodeFactory.createSinkIn2<String, String>(")
            appendLine("            name = name,")
            appendLine("            consume = { result, error ->")
            appendLine("                ${pluralName}State._result.value = result")
            appendLine("                ${pluralName}State._error.value = error")
            appendLine("            }")
            appendLine("        )")
            appendLine("    }")
            appendLine("}")
        }
    }
}
