/*
 * ModuleRuntimeGenerator
 * Generates `{Module}Runtime.kt` — the single per-module file that replaces
 * the eliminated thick-stack trio (Controller.kt + Adapter.kt + Flow.kt).
 *
 * Output structure (per data-model.md §4 / contracts/universal-runtime.md):
 *   - `object {Module}NodeRegistry` exposing `fun lookup(name: String): CodeNodeDefinition?`
 *     with one `when` arm per CodeNode in the FlowGraph
 *   - `fun create{Module}Runtime(flowGraph: FlowGraph): {Module}ControllerInterface`
 *     constructing a `DynamicPipelineController` and returning an `object` expression
 *     that delegates `ModuleController` to the controller and overrides typed
 *     state-flow getters to read directly from `{Module}State.{x}Flow`.
 *
 * License: Apache 2.0
 */

package io.codenode.flowgraphgenerate.generator

import io.codenode.fbpdsl.model.CodeNode
import io.codenode.fbpdsl.model.FlowGraph

/**
 * Generates the `{Module}Runtime.kt` file content from a FlowGraph plus the
 * package layout defined by the module's `GenerationConfig`.
 *
 * Introduced by feature 085 (universal-runtime collapse). Replaces the
 * `RuntimeControllerGenerator` + `RuntimeControllerAdapterGenerator` +
 * `RuntimeFlowGenerator` triad with a single ~30-line generated file.
 */
class ModuleRuntimeGenerator {

    private val observableStateResolver = ObservableStateResolver()

    /**
     * @param flowGraph The user's FlowGraph (provides node names + their
     *        `_codeNodeClass` configuration entries to populate the registry).
     * @param basePackage Top-level module package (e.g., `io.codenode.stopwatch`).
     *        Retained for signature compatibility; the generated file now lives
     *        under [controllerPackage].
     * @param controllerPackage Subpackage holding the typed `{Module}ControllerInterface`
     *        — this is where the generated `{Module}Runtime.kt` file lives.
     * @param viewModelPackage Subpackage holding the `{Module}State` object.
     */
    fun generate(
        flowGraph: FlowGraph,
        basePackage: String,
        controllerPackage: String,
        viewModelPackage: String
    ): String {
        val moduleName = flowGraph.name.pascalCase()
        val codeNodes = flowGraph.getAllCodeNodes()
        // Match exactly what RuntimeControllerInterfaceGenerator declares on the
        // interface — every observable property (both source-output and sink-input
        // boundary ports) must be overridden so Kotlin's `ModuleController by controller`
        // delegation has nothing to satisfy beyond the inherited control surface.
        val observableProps = observableStateResolver.getObservableStateProperties(flowGraph)

        return buildString {
            generateHeader(moduleName)
            generatePackage(controllerPackage)
            generateImports(codeNodes, moduleName, viewModelPackage)
            appendLine()
            generateNodeRegistry(moduleName, codeNodes)
            appendLine()
            generateFactoryFunction(moduleName, observableProps)
        }
    }

    // ========== Header / package / imports ==========

    private fun StringBuilder.generateHeader(moduleName: String) {
        appendLine("/*")
        appendLine(" * ${moduleName}Runtime — Universal-runtime factory for the $moduleName module")
        appendLine(" * Generated by CodeNodeIO ModuleRuntimeGenerator")
        appendLine(" * License: Apache 2.0")
        appendLine(" */")
        appendLine()
    }

    private fun StringBuilder.generatePackage(basePackage: String) {
        appendLine("package $basePackage")
        appendLine()
    }

    private fun StringBuilder.generateImports(
        codeNodes: List<CodeNode>,
        moduleName: String,
        viewModelPackage: String
    ) {
        appendLine("import io.codenode.fbpdsl.model.FlowGraph")
        appendLine("import io.codenode.fbpdsl.runtime.CodeNodeDefinition")
        appendLine("import io.codenode.fbpdsl.runtime.DynamicPipelineController")
        appendLine("import io.codenode.fbpdsl.runtime.ModuleController")
        // {Module}ControllerInterface lives in this same controller package — no import needed.
        appendLine("import $viewModelPackage.${moduleName}State")
        // Per-node CodeNodeDefinition imports (sorted for determinism)
        codeNodes
            .mapNotNull { it.configuration["_codeNodeClass"] }
            .toSortedSet()
            .forEach { fqcn -> appendLine("import $fqcn") }
    }

    // ========== object {Module}NodeRegistry ==========

    private fun StringBuilder.generateNodeRegistry(moduleName: String, codeNodes: List<CodeNode>) {
        appendLine("/**")
        appendLine(" * Module-local lookup for resolving node names to compiled CodeNodeDefinitions.")
        appendLine(" * Used by [DynamicPipelineController] when running this module without the GraphEditor.")
        appendLine(" */")
        appendLine("object ${moduleName}NodeRegistry {")
        appendLine("    fun lookup(name: String): CodeNodeDefinition? = when (name) {")
        codeNodes.forEach { node ->
            val fqcn = node.configuration["_codeNodeClass"] ?: return@forEach
            val simpleName = fqcn.substringAfterLast('.')
            appendLine("        \"${node.name}\" -> $simpleName")
        }
        appendLine("        else -> null")
        appendLine("    }")
        appendLine("}")
    }

    // ========== fun create{Module}Runtime(...) ==========

    private fun StringBuilder.generateFactoryFunction(
        moduleName: String,
        sinkInputProps: List<ObservableProperty>
    ) {
        appendLine("/**")
        appendLine(" * Constructs a ${moduleName}ControllerInterface backed by [DynamicPipelineController].")
        appendLine(" *")
        appendLine(" * Production-app consumers call this directly. The returned object delegates")
        appendLine(" * every [ModuleController] member to the underlying controller and reads typed")
        appendLine(" * state flows directly from ${moduleName}State.")
        appendLine(" */")
        appendLine("fun create${moduleName}Runtime(flowGraph: FlowGraph): ${moduleName}ControllerInterface {")
        appendLine("    val controller = DynamicPipelineController(")
        appendLine("        flowGraphProvider = { flowGraph },")
        appendLine("        lookup = ${moduleName}NodeRegistry::lookup,")
        appendLine("        onReset = ${moduleName}State::reset")
        appendLine("    )")
        appendLine("    return object : ${moduleName}ControllerInterface, ModuleController by controller {")
        sinkInputProps.forEach { prop ->
            appendLine("        override val ${prop.name} = ${moduleName}State.${prop.name}Flow")
        }
        appendLine("    }")
        appendLine("}")
    }

}
