/*
 * PreviewProviderGenerator
 * Emits `userInterface/{Module}PreviewProvider.kt` (jvmMain) — the JVM-only
 * registration object that hooks the module's UI composable into
 * `io.codenode.previewapi.PreviewRegistry`.
 *
 * Why jvmMain: the GraphEditor's Runtime Preview is desktop-only (JVM), and
 * `preview-api` is consumed only from `jvmMain`. The generated PreviewProvider
 * therefore lives alongside the JVM-side module scaffolding so that mobile
 * targets (Android, iOS) don't pull in a desktop-only dependency.
 *
 * License: Apache 2.0
 */

package io.codenode.flowgraphgenerate.generator

import io.codenode.fbpdsl.model.FlowGraph

/**
 * Generates the `{Module}PreviewProvider.kt` file content.
 *
 * The output registers a single composable — `{Module}` from
 * `userInterface/{Module}.kt` — driven by `{Module}ViewModel`. This matches
 * the convention used by every regenerated reference module in DemoProject.
 *
 * Modules whose top-level composable diverges from the module name (e.g.,
 * WeatherForecast → `WeatherForecastUI`) can rename the registered
 * composable after generation; the generator emits the convention default.
 */
class PreviewProviderGenerator {

    /**
     * @param flowGraph Source of the module name. Only `flowGraph.name` is read.
     * @param basePackage Top-level module package (e.g., `io.codenode.stopwatch`).
     *        `userInterface` is appended to form the file's package.
     * @param viewModelPackage Subpackage holding `{Module}ViewModel`.
     */
    fun generate(
        flowGraph: FlowGraph,
        basePackage: String,
        viewModelPackage: String
    ): String {
        val moduleName = flowGraph.name.pascalCase()
        val userInterfacePackage = "$basePackage.userInterface"

        return buildString {
            appendLine("/*")
            appendLine(" * ${moduleName}PreviewProvider — Registers $moduleName preview composables for the runtime panel")
            appendLine(" * Generated by CodeNodeIO PreviewProviderGenerator")
            appendLine(" * License: Apache 2.0")
            appendLine(" */")
            appendLine()
            appendLine("package $userInterfacePackage")
            appendLine()
            appendLine("import $viewModelPackage.${moduleName}ViewModel")
            appendLine("import io.codenode.previewapi.PreviewRegistry")
            appendLine()
            appendLine("/**")
            appendLine(" * Provides preview composables that render $moduleName components,")
            appendLine(" * driven by the RuntimeSession's ViewModel state.")
            appendLine(" */")
            appendLine("object ${moduleName}PreviewProvider {")
            appendLine()
            appendLine("    /**")
            appendLine("     * Registers $moduleName preview composables with the PreviewRegistry.")
            appendLine("     */")
            appendLine("    fun register() {")
            appendLine("        PreviewRegistry.register(\"$moduleName\") { viewModel, modifier ->")
            appendLine("            val vm = viewModel as ${moduleName}ViewModel")
            appendLine("            $moduleName(viewModel = vm, modifier = modifier)")
            appendLine("        }")
            appendLine("    }")
            appendLine("}")
        }
    }
}
