/*
 * PreviewProviderGenerator
 * Emits `userInterface/{Module}PreviewProvider.kt` (jvmMain) — the JVM-only
 * registration object that hooks the module's UI composable into
 * `io.codenode.previewapi.PreviewRegistry`.
 *
 * Why jvmMain: the GraphEditor's Runtime Preview is desktop-only (JVM), and
 * `preview-api` is consumed only from `jvmMain`. The generated PreviewProvider
 * therefore lives alongside the JVM-side module scaffolding so that mobile
 * targets (Android, iOS) don't pull in a desktop-only dependency.
 *
 * License: Apache 2.0
 */

package io.codenode.flowgraphgenerate.generator

import io.codenode.fbpdsl.model.FlowGraph

/**
 * Generates the `{Module}PreviewProvider.kt` file content.
 *
 * The output registers a single composable — `{Module}` from
 * `userInterface/{Module}.kt` — driven by `{Module}ViewModel`. This matches
 * the convention used by every regenerated reference module in DemoProject.
 *
 * Modules whose top-level composable diverges from the module name (e.g.,
 * WeatherForecast → `WeatherForecastUI`) can rename the registered
 * composable after generation; the generator emits the convention default.
 */
class PreviewProviderGenerator {

    /**
     * @param flowGraph Source of the **flow-graph prefix** (`flowGraph.name.pascalCase()`).
     *        Drives generated-file prefix, `PreviewRegistry` key, ViewModel cast type, and
     *        — when [composableName] is null — the in-lambda Composable function call.
     * @param basePackage Top-level module package (e.g., `io.codenode.stopwatch`).
     *        `userInterface` is appended to form the file's package.
     * @param viewModelPackage Subpackage holding `{FlowGraph}ViewModel`.
     * @param composableName Optional override for the user-authored Composable function name
     *        invoked inside the `register { ... }` lambda. When null, falls back to the flow-graph
     *        prefix (the entity-module convention `composableName == flowGraphPrefix`). Post-082/083,
     *        UI-FBP modules pass the parser-extracted Composable function name here so the registry
     *        key (flow-graph prefix) can decouple from the function call (user-authored name) per
     *        feature 084 spec Session 2026-04-28 Decision 2.
     */
    fun generate(
        flowGraph: FlowGraph,
        basePackage: String,
        viewModelPackage: String,
        composableName: String? = null
    ): String {
        val flowGraphPrefix = flowGraph.name.pascalCase()
        val invokedComposable = composableName ?: flowGraphPrefix
        val userInterfacePackage = "$basePackage.userInterface"

        return buildString {
            appendLine("/*")
            appendLine(" * ${flowGraphPrefix}PreviewProvider — Registers $flowGraphPrefix preview composables for the runtime panel")
            appendLine(" * Generated by CodeNodeIO PreviewProviderGenerator")
            appendLine(" * License: Apache 2.0")
            appendLine(" */")
            appendLine()
            appendLine("package $userInterfacePackage")
            appendLine()
            appendLine("import $viewModelPackage.${flowGraphPrefix}ViewModel")
            appendLine("import io.codenode.previewapi.PreviewRegistry")
            appendLine()
            appendLine("/**")
            appendLine(" * Provides preview composables that render $flowGraphPrefix components,")
            appendLine(" * driven by the RuntimeSession's ViewModel state.")
            appendLine(" */")
            appendLine("object ${flowGraphPrefix}PreviewProvider {")
            appendLine()
            appendLine("    /**")
            appendLine("     * Registers $flowGraphPrefix preview composables with the PreviewRegistry.")
            appendLine("     */")
            appendLine("    fun register() {")
            appendLine("        PreviewRegistry.register(\"$flowGraphPrefix\") { viewModel, modifier ->")
            appendLine("            val vm = viewModel as ${flowGraphPrefix}ViewModel")
            appendLine("            $invokedComposable(viewModel = vm, modifier = modifier)")
            appendLine("        }")
            appendLine("    }")
            appendLine("}")
        }
    }
}
