/*
 * RuntimeControllerInterfaceGenerator
 * Generates {Name}ControllerInterface.kt from FlowGraph
 * License: Apache 2.0
 */

package io.codenode.flowgraphgenerate.generator

import io.codenode.fbpdsl.model.FlowGraph

/**
 * Generates a {Name}ControllerInterface.kt file declaring the same control
 * methods and StateFlow properties as the Controller.
 *
 * The generated interface:
 * - Declares StateFlow properties for executionState and observable state
 * - Declares control method signatures (start, stop, reset, pause, resume)
 * - Enables dependency injection and testing with fakes
 */
class RuntimeControllerInterfaceGenerator {

    private val observableStateResolver = ObservableStateResolver()

    /**
     * Generates the {Name}ControllerInterface.kt file content from a FlowGraph.
     *
     * @param flowGraph The flow graph to generate from
     * @param generatedPackage The package name for the generated file
     * @return Generated Kotlin source code
     */
    fun generate(flowGraph: FlowGraph, generatedPackage: String): String {
        val flowName = flowGraph.name.pascalCase()
        val observableProps = observableStateResolver.getObservableStateProperties(flowGraph)

        return buildString {
            generateHeader(flowName)
            generatePackage(generatedPackage)
            generateImports()
            appendLine()
            generateKDoc(flowName)
            // Feature 085: extend ModuleController so consumers reach setAttenuationDelay
            // / observers / getStatus through the typed surface (instead of having to cast
            // to the now-eliminated concrete {Module}Controller class).
            appendLine("interface ${flowName}ControllerInterface : ModuleController {")
            appendLine()

            if (observableProps.isNotEmpty()) {
                generateObservableStateDeclarations(observableProps)
            }

            // executionState + start/stop/pause/resume/reset are inherited from ModuleController.

            appendLine("}")
            appendLine()
        }
    }

    private fun StringBuilder.generateHeader(flowName: String) {
        appendLine("/*")
        appendLine(" * ${flowName}ControllerInterface")
        appendLine(" * Generated by CodeNodeIO RuntimeControllerInterfaceGenerator")
        appendLine(" * License: Apache 2.0")
        appendLine(" */")
        appendLine()
    }

    private fun StringBuilder.generatePackage(generatedPackage: String) {
        appendLine("package $generatedPackage")
        appendLine()
    }

    private fun StringBuilder.generateImports() {
        appendLine("import io.codenode.fbpdsl.model.FlowGraph")
        appendLine("import io.codenode.fbpdsl.runtime.ModuleController")
        appendLine("import kotlinx.coroutines.flow.StateFlow")
    }

    private fun StringBuilder.generateKDoc(flowName: String) {
        appendLine("/**")
        appendLine(" * Interface defining the contract for $flowName controllers.")
        appendLine(" *")
        appendLine(" * Enables dependency injection and testing by allowing")
        appendLine(" * both the real ${flowName}Controller and test fakes to be used.")
        appendLine(" *")
        appendLine(" * @generated by CodeNodeIO RuntimeControllerInterfaceGenerator")
        appendLine(" */")
    }

    private fun StringBuilder.generateObservableStateDeclarations(observableProps: List<ObservableProperty>) {
        observableProps.forEach { prop ->
            val typeStr = if (prop.defaultValue == "null") "${prop.typeName}?" else prop.typeName
            appendLine("    val ${prop.name}: StateFlow<$typeStr>")
        }
        appendLine()
    }

}
