/*
 * UIFBPViewModelGenerator — feature 087 / FR-003 / Design B.
 *
 * Emits the MVI-shaped ViewModel:
 *   - private val _state = MutableStateFlow({Name}State()); val state = _state.asStateFlow()
 *   - init { viewModelScope.launch { controller.<sinkPort>.collect { _state.update { copy(...) } } } } per sinkInput
 *   - fun onEvent(event: {Name}Event) { when (event) { is Update<P> -> controller.emit<P>(event.value) ; <P> -> controller.emit<P>() } }
 *   - forwarding control surface (start/stop/pause/resume/reset) — preserved unchanged
 *
 * No singleton-State writes anywhere. The ViewModel's _state is the genuine
 * SSOT for the UI; controller emit methods are the genuine SSOT for the
 * runtime side. See contracts/viewmodel-generator.md.
 *
 * License: Apache 2.0
 */

package io.codenode.flowgraphgenerate.generator

import io.codenode.flowgraphgenerate.parser.PortInfo
import io.codenode.flowgraphgenerate.parser.UIFBPSpec

class UIFBPViewModelGenerator {

    /** Emits `{basePackage}.viewmodel.{Name}ViewModel` per FR-003. */
    fun generate(spec: UIFBPSpec): String {
        val sb = StringBuilder()
        val name = spec.flowGraphPrefix
        val viewModelName = "${name}ViewModel"
        val controllerInterfaceName = "${name}ControllerInterface"
        val stateName = "${name}State"
        val eventName = "${name}Event"

        sb.appendLine("/*")
        sb.appendLine(" * $viewModelName")
        sb.appendLine(" * Generated by CodeNodeIO UIFBPViewModelGenerator (feature 087 / Design B)")
        sb.appendLine(" * License: Apache 2.0")
        sb.appendLine(" */")
        sb.appendLine()
        sb.appendLine("package ${spec.packageName}.viewmodel")
        sb.appendLine()
        sb.appendLine("import androidx.lifecycle.ViewModel")
        sb.appendLine("import androidx.lifecycle.viewModelScope")
        sb.appendLine("import io.codenode.fbpdsl.model.ExecutionState")
        sb.appendLine("import io.codenode.fbpdsl.model.FlowGraph")
        sb.appendLine("import kotlinx.coroutines.flow.MutableStateFlow")
        sb.appendLine("import kotlinx.coroutines.flow.StateFlow")
        sb.appendLine("import kotlinx.coroutines.flow.asStateFlow")
        sb.appendLine("import kotlinx.coroutines.flow.update")
        sb.appendLine("import kotlinx.coroutines.launch")
        sb.appendLine("import ${spec.packageName}.controller.$controllerInterfaceName")

        // IP-type imports — only when at least one sinkInput or VALUED sourceOutput needs them.
        val needed = (spec.sinkInputs.map { it.typeName } +
            spec.sourceOutputs.filter { it.typeName != "Unit" }.map { it.typeName }).toSet()
        for (imp in spec.ipTypeImports.filter { needed.contains(it.substringAfterLast('.')) }) {
            sb.appendLine("import $imp")
        }

        sb.appendLine()
        sb.appendLine("class $viewModelName(")
        sb.appendLine("    private val controller: $controllerInterfaceName")
        sb.appendLine(") : ViewModel() {")
        sb.appendLine()
        sb.appendLine("    private val _state = MutableStateFlow($stateName())")
        sb.appendLine("    val state: StateFlow<$stateName> = _state.asStateFlow()")
        sb.appendLine()
        sb.appendLine("    val executionState: StateFlow<ExecutionState> = controller.executionState")

        // Per-sinkInput collector — fold each emission into _state via copy(...).
        if (spec.sinkInputs.isNotEmpty()) {
            sb.appendLine()
            sb.appendLine("    init {")
            for (sink in spec.sinkInputs) {
                sb.appendLine("        viewModelScope.launch {")
                sb.appendLine("            controller.${sink.name}.collect { value ->")
                sb.appendLine("                _state.update { it.copy(${sink.name} = value) }")
                sb.appendLine("            }")
                sb.appendLine("        }")
            }
            sb.appendLine("    }")
        }

        // onEvent dispatcher — exhaustive when over every Event case.
        sb.appendLine()
        sb.appendLine("    fun onEvent(event: $eventName) {")
        sb.appendLine("        when (event) {")
        for (port in spec.sourceOutputs) {
            val caseName = pascal(port.name)
            if (port.typeName == "Unit") {
                sb.appendLine("            $eventName.$caseName -> controller.emit$caseName()")
            } else {
                sb.appendLine("            is $eventName.Update$caseName -> controller.emit$caseName(event.value)")
            }
        }
        sb.appendLine("        }")
        sb.appendLine("    }")

        // Forwarding control surface (preserved unchanged from feature 084).
        sb.appendLine()
        sb.appendLine("    fun start(): FlowGraph = controller.start()")
        sb.appendLine("    fun stop(): FlowGraph = controller.stop()")
        sb.appendLine("    fun pause(): FlowGraph = controller.pause()")
        sb.appendLine("    fun resume(): FlowGraph = controller.resume()")
        sb.appendLine("    fun reset(): FlowGraph = controller.reset()")
        sb.appendLine("}")

        return sb.toString()
    }

    /** Uppercases the first character of [name]; leaves the rest as-is. */
    private fun pascal(name: String): String =
        if (name.isEmpty()) name
        else name.replaceFirstChar { it.uppercase() }
}
