/*
 * UIFBPSourceCodeNodeGenerator - Generates {Name}SourceCodeNode.kt from UIFBPSpec
 * License: Apache 2.0
 */

package io.codenode.flowgraphgenerate.generator

import io.codenode.flowgraphgenerate.parser.UIFBPSpec

class UIFBPSourceCodeNodeGenerator {

    fun generate(spec: UIFBPSpec): String? {
        if (spec.sourceOutputs.isEmpty()) return null

        val sb = StringBuilder()
        val outputs = spec.sourceOutputs
        val objectName = "${spec.flowGraphPrefix}SourceCodeNode"
        val nodeName = "${spec.flowGraphPrefix}Source"

        sb.appendLine("/*")
        sb.appendLine(" * $objectName - Source node for ${spec.flowGraphPrefix} UI inputs")
        sb.appendLine(" * Generated by CodeNodeIO UIFBPInterfaceGenerator")
        sb.appendLine(" * License: Apache 2.0")
        sb.appendLine(" */")
        sb.appendLine()
        sb.appendLine("package ${spec.packageName}.nodes")
        sb.appendLine()
        sb.appendLine("import ${spec.packageName}.viewmodel.${spec.flowGraphPrefix}State")
        sb.appendLine("import io.codenode.fbpdsl.model.CodeNodeFactory")
        sb.appendLine("import io.codenode.fbpdsl.runtime.CodeNodeDefinition")
        sb.appendLine("import io.codenode.fbpdsl.model.CodeNodeType")
        sb.appendLine("import io.codenode.fbpdsl.runtime.NodeRuntime")
        sb.appendLine("import io.codenode.fbpdsl.runtime.PortSpec")

        if (outputs.size >= 2) {
            sb.appendLine("import io.codenode.fbpdsl.runtime.ProcessResult${outputs.size}")
        }
        sb.appendLine("import kotlinx.coroutines.flow.drop")
        sb.appendLine("import kotlinx.coroutines.flow.combine")

        for (imp in spec.ipTypeImports) {
            val typeName = imp.substringAfterLast(".")
            if (outputs.any { it.typeName == typeName }) {
                sb.appendLine("import $imp")
            }
        }

        sb.appendLine()
        sb.appendLine("object $objectName : CodeNodeDefinition {")
        sb.appendLine("    override val name = \"$nodeName\"")
        sb.appendLine("    override val category = CodeNodeType.SOURCE")
        sb.appendLine("    override val description = \"Emits UI input values into the processing graph\"")
        sb.appendLine("    override val inputPorts = emptyList<PortSpec>()")
        sb.appendLine("    override val outputPorts = listOf(")
        for ((i, port) in outputs.withIndex()) {
            val comma = if (i < outputs.size - 1) "," else ""
            sb.appendLine("        PortSpec(\"${port.name}\", ${port.typeName}::class)$comma")
        }
        sb.appendLine("    )")
        sb.appendLine()
        sb.appendLine("    override fun createRuntime(name: String): NodeRuntime {")

        when (outputs.size) {
            1 -> generateSingleOutputRuntime(sb, spec, outputs)
            2 -> generateMultiOutputRuntime(sb, spec, outputs, 2)
            3 -> generateMultiOutputRuntime(sb, spec, outputs, 3)
            else -> generateSingleOutputRuntime(sb, spec, outputs)
        }

        sb.appendLine("    }")
        sb.appendLine("}")

        return sb.toString()
    }

    private fun generateSingleOutputRuntime(sb: StringBuilder, spec: UIFBPSpec, outputs: List<io.codenode.flowgraphgenerate.parser.PortInfo>) {
        val port = outputs[0]
        sb.appendLine("        return CodeNodeFactory.createContinuousSource<${port.typeName}>(")
        sb.appendLine("            name = name,")
        sb.appendLine("            generate = { emit ->")
        sb.appendLine("                ${spec.flowGraphPrefix}State._${port.name}")
        sb.appendLine("                    .drop(1)")
        sb.appendLine("                    .collect { value ->")
        sb.appendLine("                        emit(value)")
        sb.appendLine("                    }")
        sb.appendLine("            }")
        sb.appendLine("        )")
    }

    private fun generateMultiOutputRuntime(sb: StringBuilder, spec: UIFBPSpec, outputs: List<io.codenode.flowgraphgenerate.parser.PortInfo>, count: Int) {
        val typeParams = outputs.joinToString(", ") { it.typeName }
        sb.appendLine("        return CodeNodeFactory.createSourceOut$count<$typeParams>(")
        sb.appendLine("            name = name,")
        sb.appendLine("            generate = { emit ->")

        val flows = outputs.joinToString(",\n                ") { "${spec.flowGraphPrefix}State._${it.name}" }
        sb.appendLine("                combine(")
        sb.appendLine("                $flows")
        sb.appendLine("                ) { values -> values }")
        sb.appendLine("                    .drop(1)")
        sb.appendLine("                    .collect {")

        val args = outputs.mapIndexed { i, port ->
            "${spec.flowGraphPrefix}State._${port.name}.value"
        }
        val resultCall = if (count == 2) {
            "ProcessResult$count(${args[0]}, ${args[1]})"
        } else {
            "ProcessResult$count(${args.joinToString(", ")})"
        }
        sb.appendLine("                        emit($resultCall)")
        sb.appendLine("                    }")
        sb.appendLine("            }")
        sb.appendLine("        )")
    }
}
