/*
 * UIFBPStateGenerator — feature 087 / Design B.
 *
 * Emits the public immutable `data class {Name}State` (FR-001). One `val`
 * property per `spec.sinkInputs` entry, in declared order, with default
 * values per the contract's table. The prior singleton-object emission is
 * gone; per-flow-graph runtime state lives in {Name}Runtime's closure
 * (Decision 8). The State data class is the genuine SSOT for the UI.
 *
 * License: Apache 2.0
 */

package io.codenode.flowgraphgenerate.generator

import io.codenode.flowgraphgenerate.parser.PortInfo
import io.codenode.flowgraphgenerate.parser.UIFBPSpec

class UIFBPStateGenerator {

    /**
     * Emits `{basePackage}.viewmodel.{Name}State` as an immutable Kotlin
     * `data class` whose properties mirror [UIFBPSpec.sinkInputs] in
     * declared order. Defaults follow the table in
     * `contracts/state-generator.md`.
     *
     * Edge case (spec L135-138): a non-nullable port carrying a non-primitive
     * IP type (no derivable no-arg default) falls back to a nullable property
     * with `null` default. Authors who need a non-null default override
     * post-generation.
     */
    fun generate(spec: UIFBPSpec): String {
        val sb = StringBuilder()
        val stateClassName = "${spec.flowGraphPrefix}State"

        sb.appendLine("/*")
        sb.appendLine(" * $stateClassName")
        sb.appendLine(" * Generated by CodeNodeIO UIFBPStateGenerator (feature 087 / Design B)")
        sb.appendLine(" * License: Apache 2.0")
        sb.appendLine(" */")
        sb.appendLine()
        sb.appendLine("package ${spec.packageName}.viewmodel")

        // IP-type imports — only when at least one sinkInput references one.
        val needed = spec.sinkInputs.map { it.typeName }.toSet()
        val imports = spec.ipTypeImports.filter { imp -> needed.contains(imp.substringAfterLast('.')) }
        if (imports.isNotEmpty()) {
            sb.appendLine()
            for (imp in imports) {
                sb.appendLine("import $imp")
            }
        }

        sb.appendLine()
        if (spec.sinkInputs.isEmpty()) {
            // FR-009 zero-arg data class.
            sb.appendLine("data class $stateClassName()")
        } else {
            sb.appendLine("data class $stateClassName(")
            for ((i, port) in spec.sinkInputs.withIndex()) {
                val (typeStr, defaultExpr) = propertyShape(port)
                val comma = if (i < spec.sinkInputs.size - 1) "," else ""
                sb.appendLine("    val ${port.name}: $typeStr = $defaultExpr$comma")
            }
            sb.appendLine(")")
        }

        return sb.toString()
    }

    /**
     * Returns `(propertyType, defaultExpression)` for a port. Primitives use
     * their canonical zero/empty defaults; declared-nullable ports stay
     * nullable with `null`; non-primitive non-nullable ports fall back to
     * nullable + `null` per spec edge case.
     */
    private fun propertyShape(port: PortInfo): Pair<String, String> {
        if (port.isNullable) return "${port.typeName}?" to "null"
        return when (port.typeName) {
            "Int" -> "Int" to "0"
            "Long" -> "Long" to "0L"
            "Double" -> "Double" to "0.0"
            "Float" -> "Float" to "0.0f"
            "Boolean" -> "Boolean" to "false"
            "String" -> "String" to "\"\""
            "Unit" -> "Unit" to "Unit"
            else -> "${port.typeName}?" to "null"
        }
    }
}
