/*
 * UIFBPViewModelGenerator - Generates {FlowGraph}ViewModel.kt from UIFBPSpec
 *
 * Post-feature-085 shape (matches WeatherForecast/Addresses entity-module ViewModels):
 *   - emitted at {basePackage}.viewmodel.{FlowGraph}ViewModel
 *   - constructor: (private val controller: {FlowGraph}ControllerInterface) — drives the
 *     reflection match in ModuleSessionFactory.tryCreateViewModel
 *   - state-flow members read directly from {FlowGraph}State.{y}Flow
 *   - emit(...) writes to {FlowGraph}State._x mutable fields
 *   - forwarding control methods delegate one-to-one to the controller (the UI calls
 *     viewModel.start() etc. directly per US1.AS3 / US2.AS3)
 *
 * License: Apache 2.0
 */

package io.codenode.flowgraphgenerate.generator

import io.codenode.flowgraphgenerate.parser.UIFBPSpec

class UIFBPViewModelGenerator {

    fun generate(spec: UIFBPSpec): String {
        val sb = StringBuilder()
        val viewModelTypeName = "${spec.flowGraphPrefix}ViewModel"
        val controllerInterfaceTypeName = "${spec.flowGraphPrefix}ControllerInterface"
        val stateObjectName = "${spec.flowGraphPrefix}State"
        val viewModelPackage = "${spec.packageName}.viewmodel"
        val controllerPackage = "${spec.packageName}.controller"

        sb.appendLine("/*")
        sb.appendLine(" * $viewModelTypeName")
        sb.appendLine(" * Generated by CodeNodeIO UIFBPViewModelGenerator")
        sb.appendLine(" * License: Apache 2.0")
        sb.appendLine(" */")
        sb.appendLine()
        sb.appendLine("package $viewModelPackage")
        sb.appendLine()
        sb.appendLine("import androidx.lifecycle.ViewModel")
        sb.appendLine("import io.codenode.fbpdsl.model.ExecutionState")
        sb.appendLine("import io.codenode.fbpdsl.model.FlowGraph")
        sb.appendLine("import kotlinx.coroutines.flow.StateFlow")
        sb.appendLine("import $controllerPackage.$controllerInterfaceTypeName")

        for (imp in spec.ipTypeImports) {
            sb.appendLine("import $imp")
        }

        sb.appendLine()
        sb.appendLine("class $viewModelTypeName(")
        sb.appendLine("    private val controller: $controllerInterfaceTypeName")
        sb.appendLine(") : ViewModel() {")
        sb.appendLine()

        // Sink-input flows read directly from State (matches WeatherForecast/Addresses precedent).
        for (sink in spec.sinkInputs) {
            val typeStr = if (sink.isNullable) "${sink.typeName}?" else sink.typeName
            sb.appendLine("    val ${sink.name}: StateFlow<$typeStr> = $stateObjectName.${sink.name}Flow")
        }

        // executionState forwarded from the controller's inherited ModuleController surface.
        sb.appendLine("    val executionState: StateFlow<ExecutionState> = controller.executionState")

        // Source emit — writes to State mutable fields (UI → State → SourceCodeNode).
        if (spec.sourceOutputs.isNotEmpty()) {
            sb.appendLine()
            val params = spec.sourceOutputs.joinToString(", ") { "${it.name}: ${it.typeName}" }
            sb.appendLine("    fun emit($params) {")
            for (port in spec.sourceOutputs) {
                sb.appendLine("        $stateObjectName._${port.name}.value = ${port.name}")
            }
            sb.appendLine("    }")
        }

        // Forwarding control surface — the UI invokes these directly (US1.AS3, US2.AS3).
        sb.appendLine()
        sb.appendLine("    fun start(): FlowGraph = controller.start()")
        sb.appendLine("    fun stop(): FlowGraph = controller.stop()")
        sb.appendLine("    fun pause(): FlowGraph = controller.pause()")
        sb.appendLine("    fun resume(): FlowGraph = controller.resume()")
        sb.appendLine("    fun reset(): FlowGraph = controller.reset()")
        sb.appendLine("}")

        return sb.toString()
    }
}
