/*
 * UIFBPSinkCodeNodeGenerator — feature 087 / Decision 8.
 *
 * Emits `object {Name}SinkCodeNode : CodeNodeDefinition` with:
 *   - default no-op `createRuntime` (safe to drop on the GraphEditor palette
 *     outside a UI-FBP runtime context)
 *   - `fun withReporters(vararg reporters: (Any?) -> Unit): CodeNodeDefinition`
 *     — per-flow-graph wrapper that the Runtime factory uses to inject one
 *     callback per sinkInput. The wrapper returns a delegated CodeNodeDefinition
 *     (`object : CodeNodeDefinition by this`) preserving discovery identity
 *     while overriding `createRuntime` to capture the reporters.
 *
 * No singleton-State writes anywhere. See contracts/source-sink-controller-runtime.md.
 *
 * License: Apache 2.0
 */

package io.codenode.flowgraphgenerate.generator

import io.codenode.flowgraphgenerate.parser.PortInfo
import io.codenode.flowgraphgenerate.parser.UIFBPSpec

class UIFBPSinkCodeNodeGenerator {

    fun generate(spec: UIFBPSpec): String? {
        if (spec.sinkInputs.isEmpty()) return null

        val sb = StringBuilder()
        val inputs = spec.sinkInputs
        val objectName = "${spec.flowGraphPrefix}SinkCodeNode"
        val nodeName = "${spec.flowGraphPrefix}Sink"

        sb.appendLine("/*")
        sb.appendLine(" * $objectName — Sink node for ${spec.flowGraphPrefix} UI display.")
        sb.appendLine(" * Generated by CodeNodeIO UIFBPSinkCodeNodeGenerator (feature 087 / Decision 8)")
        sb.appendLine(" * License: Apache 2.0")
        sb.appendLine(" */")
        sb.appendLine()
        sb.appendLine("package ${spec.packageName}.nodes")
        sb.appendLine()
        sb.appendLine("import io.codenode.fbpdsl.model.CodeNodeFactory")
        sb.appendLine("import io.codenode.fbpdsl.model.CodeNodeType")
        sb.appendLine("import io.codenode.fbpdsl.runtime.CodeNodeDefinition")
        sb.appendLine("import io.codenode.fbpdsl.runtime.NodeRuntime")
        sb.appendLine("import io.codenode.fbpdsl.runtime.PortSpec")

        // IP-type imports — only for sinkInputs that reference custom types.
        val needed = inputs.map { it.typeName }.toSet()
        for (imp in spec.ipTypeImports.filter { needed.contains(it.substringAfterLast('.')) }) {
            sb.appendLine("import $imp")
        }

        sb.appendLine()
        sb.appendLine("object $objectName : CodeNodeDefinition {")
        sb.appendLine("    override val name = \"$nodeName\"")
        sb.appendLine("    override val category = CodeNodeType.SINK")
        sb.appendLine("    override val description = \"Receives processed results for ${spec.flowGraphPrefix} UI display\"")
        sb.appendLine("    override val inputPorts = listOf(")
        for ((i, port) in inputs.withIndex()) {
            val comma = if (i < inputs.size - 1) "," else ""
            sb.appendLine("        PortSpec(\"${port.name}\", ${port.typeName}::class)$comma")
        }
        sb.appendLine("    )")
        sb.appendLine("    override val outputPorts = emptyList<PortSpec>()")
        sb.appendLine()
        sb.appendLine("    /** Default runtime: no-op reporters. Safe for palette drops outside a UI-FBP runtime. */")
        sb.appendLine("    override fun createRuntime(name: String): NodeRuntime =")
        sb.appendLine("        buildRuntime(name, Array(${inputs.size}) { { _: Any? -> } })")
        sb.appendLine()
        sb.appendLine("    /**")
        sb.appendLine("     * Returns a per-flow-graph CodeNodeDefinition wrapper that delivers received")
        sb.appendLine("     * IPs to [reporters]. The Runtime factory passes one reporter per sinkInput,")
        sb.appendLine("     * in declared order. Decision 8 / Design B.")
        sb.appendLine("     */")
        sb.appendLine("    fun withReporters(vararg reporters: (Any?) -> Unit): CodeNodeDefinition =")
        sb.appendLine("        object : CodeNodeDefinition by this {")
        sb.appendLine("            override fun createRuntime(name: String): NodeRuntime =")
        sb.appendLine("                buildRuntime(name, reporters)")
        sb.appendLine("        }")
        sb.appendLine()
        sb.appendLine("    private fun buildRuntime(name: String, reporters: Array<out (Any?) -> Unit>): NodeRuntime {")
        if (inputs.size == 1) {
            sb.appendLine("        return CodeNodeFactory.createContinuousSink<${inputs[0].typeName}>(")
            sb.appendLine("            name = name,")
            sb.appendLine("            consume = { value -> reporters[0](value) }")
            sb.appendLine("        )")
        } else {
            val typeParams = inputs.joinToString(", ") { it.typeName }
            val paramNames = inputs.map { it.name }
            sb.appendLine("        return CodeNodeFactory.createSinkIn${inputs.size}<$typeParams>(")
            sb.appendLine("            name = name,")
            sb.appendLine("            consume = { ${paramNames.joinToString(", ")} ->")
            for ((i, port) in inputs.withIndex()) {
                sb.appendLine("                reporters[$i](${port.name})")
            }
            sb.appendLine("            }")
            sb.appendLine("        )")
        }
        sb.appendLine("    }")
        sb.appendLine("}")

        return sb.toString()
    }
}
