/*
 * UIFBPStateGenerator - Generates {Name}State.kt from UIFBPSpec
 * License: Apache 2.0
 */

package io.codenode.flowgraphgenerate.generator

import io.codenode.flowgraphgenerate.parser.PortInfo
import io.codenode.flowgraphgenerate.parser.UIFBPSpec

class UIFBPStateGenerator {

    fun generate(spec: UIFBPSpec): String {
        val allPorts = spec.sourceOutputs + spec.sinkInputs
        val sb = StringBuilder()

        sb.appendLine("/*")
        sb.appendLine(" * ${spec.moduleName}State")
        sb.appendLine(" * Generated by CodeNodeIO UIFBPInterfaceGenerator")
        sb.appendLine(" * License: Apache 2.0")
        sb.appendLine(" */")
        sb.appendLine()
        sb.appendLine("package ${spec.packageName}")
        sb.appendLine()
        sb.appendLine("import kotlinx.coroutines.flow.MutableStateFlow")
        sb.appendLine("import kotlinx.coroutines.flow.StateFlow")
        sb.appendLine("import kotlinx.coroutines.flow.asStateFlow")

        for (imp in spec.ipTypeImports) {
            sb.appendLine("import $imp")
        }

        sb.appendLine()
        sb.appendLine("object ${spec.moduleName}State {")
        sb.appendLine()

        for (port in allPorts) {
            val defaultValue = defaultValueFor(port)
            val typeStr = if (port.isNullable) "${port.typeName}?" else port.typeName
            sb.appendLine("    internal val _${port.name} = MutableStateFlow<$typeStr>($defaultValue)")
            sb.appendLine("    val ${port.name}Flow: StateFlow<$typeStr> = _${port.name}.asStateFlow()")
            sb.appendLine()
        }

        sb.appendLine("    fun reset() {")
        for (port in allPorts) {
            val defaultValue = defaultValueFor(port)
            sb.appendLine("        _${port.name}.value = $defaultValue")
        }
        sb.appendLine("    }")
        sb.appendLine("}")

        return sb.toString()
    }

    private fun defaultValueFor(port: PortInfo): String {
        if (port.isNullable) return "null"
        return when (port.typeName) {
            "Int" -> "0"
            "Long" -> "0L"
            "Double" -> "0.0"
            "Float" -> "0.0f"
            "Boolean" -> "false"
            "String" -> "\"\""
            else -> "null"
        }
    }
}
