/*
 * UIFBPSourceCodeNodeGenerator — feature 087 / Decision 8.
 *
 * Emits `object {Name}SourceCodeNode : CodeNodeDefinition` with:
 *   - default never-emitting `createRuntime` (safe to drop on the GraphEditor
 *     palette outside a UI-FBP runtime context)
 *   - `fun withSources(vararg sources: SharedFlow<*>): CodeNodeDefinition`
 *     — per-flow-graph wrapper that the Runtime factory uses to inject one
 *     SharedFlow per sourceOutput. The wrapper returns a delegated
 *     CodeNodeDefinition (`object : CodeNodeDefinition by this`) preserving
 *     discovery identity while overriding `createRuntime` to launch one
 *     collector per source flow.
 *
 * No singleton-State reads anywhere. See contracts/source-sink-controller-runtime.md.
 *
 * License: Apache 2.0
 */

package io.codenode.flowgraphgenerate.generator

import io.codenode.flowgraphgenerate.parser.PortInfo
import io.codenode.flowgraphgenerate.parser.UIFBPSpec

class UIFBPSourceCodeNodeGenerator {

    fun generate(spec: UIFBPSpec): String? {
        if (spec.sourceOutputs.isEmpty()) return null

        val sb = StringBuilder()
        val outputs = spec.sourceOutputs
        val objectName = "${spec.flowGraphPrefix}SourceCodeNode"
        val nodeName = "${spec.flowGraphPrefix}Source"

        sb.appendLine("/*")
        sb.appendLine(" * $objectName — Source node for ${spec.flowGraphPrefix} UI inputs.")
        sb.appendLine(" * Generated by CodeNodeIO UIFBPSourceCodeNodeGenerator (feature 087 / Decision 8)")
        sb.appendLine(" * License: Apache 2.0")
        sb.appendLine(" */")
        sb.appendLine()
        sb.appendLine("package ${spec.packageName}.nodes")
        sb.appendLine()
        sb.appendLine("import io.codenode.fbpdsl.model.CodeNodeFactory")
        sb.appendLine("import io.codenode.fbpdsl.model.CodeNodeType")
        sb.appendLine("import io.codenode.fbpdsl.runtime.CodeNodeDefinition")
        sb.appendLine("import io.codenode.fbpdsl.runtime.NodeRuntime")
        sb.appendLine("import io.codenode.fbpdsl.runtime.PortSpec")
        sb.appendLine("import kotlinx.coroutines.flow.MutableSharedFlow")
        sb.appendLine("import kotlinx.coroutines.flow.SharedFlow")
        if (outputs.size >= 2) {
            sb.appendLine("import io.codenode.fbpdsl.runtime.ProcessResult${outputs.size}")
        }

        // IP-type imports — only for sourceOutputs that reference custom non-Unit types.
        val needed = outputs.filter { it.typeName != "Unit" }.map { it.typeName }.toSet()
        for (imp in spec.ipTypeImports.filter { needed.contains(it.substringAfterLast('.')) }) {
            sb.appendLine("import $imp")
        }

        sb.appendLine()
        sb.appendLine("object $objectName : CodeNodeDefinition {")
        sb.appendLine("    override val name = \"$nodeName\"")
        sb.appendLine("    override val category = CodeNodeType.SOURCE")
        sb.appendLine("    override val description = \"Emits UI input values into the processing graph\"")
        sb.appendLine("    override val inputPorts = emptyList<PortSpec>()")
        sb.appendLine("    override val outputPorts = listOf(")
        for ((i, port) in outputs.withIndex()) {
            val comma = if (i < outputs.size - 1) "," else ""
            sb.appendLine("        PortSpec(\"${port.name}\", ${port.typeName}::class)$comma")
        }
        sb.appendLine("    )")
        sb.appendLine()
        sb.appendLine("    /** Default runtime: never-emitting sources. Safe for palette drops outside a UI-FBP runtime. */")
        sb.appendLine("    override fun createRuntime(name: String): NodeRuntime {")
        sb.appendLine("        val placeholders: Array<SharedFlow<*>> = Array(${outputs.size}) { MutableSharedFlow<Any?>() }")
        sb.appendLine("        return buildRuntime(name, placeholders)")
        sb.appendLine("    }")
        sb.appendLine()
        sb.appendLine("    /**")
        sb.appendLine("     * Returns a per-flow-graph CodeNodeDefinition wrapper that emits values from")
        sb.appendLine("     * [sources] (one SharedFlow per output port, declared order) onto the FBP")
        sb.appendLine("     * output channels. Decision 8 / Design B.")
        sb.appendLine("     */")
        sb.appendLine("    fun withSources(vararg sources: SharedFlow<*>): CodeNodeDefinition =")
        sb.appendLine("        object : CodeNodeDefinition by this {")
        sb.appendLine("            override fun createRuntime(name: String): NodeRuntime = buildRuntime(name, sources)")
        sb.appendLine("        }")
        sb.appendLine()
        sb.appendLine("    @Suppress(\"UNCHECKED_CAST\")")
        sb.appendLine("    private fun buildRuntime(name: String, sources: Array<out SharedFlow<*>>): NodeRuntime {")
        if (outputs.size == 1) {
            sb.appendLine("        return CodeNodeFactory.createContinuousSource<${outputs[0].typeName}>(")
            sb.appendLine("            name = name,")
            sb.appendLine("            generate = { emit ->")
            sb.appendLine("                (sources[0] as SharedFlow<${outputs[0].typeName}>).collect { value -> emit(value) }")
            sb.appendLine("            }")
            sb.appendLine("        )")
        } else {
            // Multi-port: use createSourceOut{N}<types> + select-style aggregation.
            // We emit a ProcessResult per upstream emission on any source; for ports that
            // didn't fire, we re-use the latest known value from a per-port cache.
            val typeParams = outputs.joinToString(", ") { it.typeName }
            sb.appendLine("        return CodeNodeFactory.createSourceOut${outputs.size}<$typeParams>(")
            sb.appendLine("            name = name,")
            sb.appendLine("            generate = { emit ->")
            sb.appendLine("                val latest = arrayOfNulls<Any?>(${outputs.size})")
            sb.appendLine("                kotlinx.coroutines.coroutineScope {")
            for ((i, port) in outputs.withIndex()) {
                sb.appendLine("                    kotlinx.coroutines.launch {")
                sb.appendLine("                        (sources[$i] as SharedFlow<${port.typeName}>).collect { value ->")
                sb.appendLine("                            latest[$i] = value")
                val args = outputs.mapIndexed { j, p ->
                    val default = defaultExpr(p)
                    "(latest[$j] as? ${p.typeName}) ?: $default"
                }.joinToString(", ")
                sb.appendLine("                            emit(ProcessResult${outputs.size}($args))")
                sb.appendLine("                        }")
                sb.appendLine("                    }")
            }
            sb.appendLine("                }")
            sb.appendLine("            }")
            sb.appendLine("        )")
        }
        sb.appendLine("    }")
        sb.appendLine("}")

        return sb.toString()
    }

    private fun defaultExpr(port: PortInfo): String {
        if (port.isNullable) return "null"
        return when (port.typeName) {
            "Int" -> "0"
            "Long" -> "0L"
            "Double" -> "0.0"
            "Float" -> "0.0f"
            "Boolean" -> "false"
            "String" -> "\"\""
            "Unit" -> "Unit"
            else -> "null"
        }
    }
}
