/*
 * UIFBPSinkCodeNodeGenerator - Generates {Name}SinkCodeNode.kt from UIFBPSpec
 * License: Apache 2.0
 */

package io.codenode.flowgraphgenerate.generator

import io.codenode.flowgraphgenerate.parser.UIFBPSpec

class UIFBPSinkCodeNodeGenerator {

    fun generate(spec: UIFBPSpec): String? {
        if (spec.sinkInputs.isEmpty()) return null

        val sb = StringBuilder()
        val inputs = spec.sinkInputs
        val objectName = "${spec.flowGraphPrefix}SinkCodeNode"
        val nodeName = "${spec.flowGraphPrefix}Sink"

        sb.appendLine("/*")
        sb.appendLine(" * $objectName - Sink node for ${spec.flowGraphPrefix} UI display")
        sb.appendLine(" * Generated by CodeNodeIO UIFBPInterfaceGenerator")
        sb.appendLine(" * License: Apache 2.0")
        sb.appendLine(" */")
        sb.appendLine()
        sb.appendLine("package ${spec.packageName}.nodes")
        sb.appendLine()
        sb.appendLine("import ${spec.packageName}.viewmodel.${spec.flowGraphPrefix}State")
        sb.appendLine("import io.codenode.fbpdsl.model.CodeNodeFactory")
        sb.appendLine("import io.codenode.fbpdsl.runtime.CodeNodeDefinition")
        sb.appendLine("import io.codenode.fbpdsl.model.CodeNodeType")
        sb.appendLine("import io.codenode.fbpdsl.runtime.NodeRuntime")
        sb.appendLine("import io.codenode.fbpdsl.runtime.PortSpec")

        for (imp in spec.ipTypeImports) {
            val typeName = imp.substringAfterLast(".")
            if (inputs.any { it.typeName == typeName }) {
                sb.appendLine("import $imp")
            }
        }

        sb.appendLine()
        sb.appendLine("object $objectName : CodeNodeDefinition {")
        sb.appendLine("    override val name = \"$nodeName\"")
        sb.appendLine("    override val category = CodeNodeType.SINK")
        sb.appendLine("    override val description = \"Receives processed results for ${spec.flowGraphPrefix} UI display\"")
        sb.appendLine("    override val inputPorts = listOf(")
        for ((i, port) in inputs.withIndex()) {
            val comma = if (i < inputs.size - 1) "," else ""
            sb.appendLine("        PortSpec(\"${port.name}\", ${port.typeName}::class)$comma")
        }
        sb.appendLine("    )")
        sb.appendLine("    override val outputPorts = emptyList<PortSpec>()")
        sb.appendLine()
        sb.appendLine("    override fun createRuntime(name: String): NodeRuntime {")

        when (inputs.size) {
            1 -> generateSingleInputRuntime(sb, spec, inputs)
            2 -> generateMultiInputRuntime(sb, spec, inputs, 2)
            3 -> generateMultiInputRuntime(sb, spec, inputs, 3)
            else -> generateSingleInputRuntime(sb, spec, inputs)
        }

        sb.appendLine("    }")
        sb.appendLine("}")

        return sb.toString()
    }

    private fun generateSingleInputRuntime(sb: StringBuilder, spec: UIFBPSpec, inputs: List<io.codenode.flowgraphgenerate.parser.PortInfo>) {
        val port = inputs[0]
        sb.appendLine("        return CodeNodeFactory.createContinuousSink<${port.typeName}>(")
        sb.appendLine("            name = name,")
        sb.appendLine("            consume = { value ->")
        sb.appendLine("                ${spec.flowGraphPrefix}State._${port.name}.value = value")
        sb.appendLine("            }")
        sb.appendLine("        )")
    }

    private fun generateMultiInputRuntime(sb: StringBuilder, spec: UIFBPSpec, inputs: List<io.codenode.flowgraphgenerate.parser.PortInfo>, count: Int) {
        val typeParams = inputs.joinToString(", ") { it.typeName }
        val paramNames = inputs.map { it.name }
        sb.appendLine("        return CodeNodeFactory.createSinkIn$count<$typeParams>(")
        sb.appendLine("            name = name,")
        sb.appendLine("            consume = { ${paramNames.joinToString(", ")} ->")
        for (port in inputs) {
            sb.appendLine("                ${spec.flowGraphPrefix}State._${port.name}.value = ${port.name}")
        }
        sb.appendLine("            }")
        sb.appendLine("        )")
    }
}
