/*
 * UIFBPViewModelGenerator - Generates {Name}ViewModel.kt from UIFBPSpec
 * License: Apache 2.0
 */

package io.codenode.flowgraphgenerate.generator

import io.codenode.flowgraphgenerate.parser.UIFBPSpec

class UIFBPViewModelGenerator {

    fun generate(spec: UIFBPSpec): String {
        val sb = StringBuilder()

        sb.appendLine("/*")
        sb.appendLine(" * ${spec.viewModelTypeName}")
        sb.appendLine(" * Generated by CodeNodeIO UIFBPInterfaceGenerator")
        sb.appendLine(" * License: Apache 2.0")
        sb.appendLine(" */")
        sb.appendLine()
        sb.appendLine("package ${spec.packageName}")
        sb.appendLine()
        sb.appendLine("import androidx.lifecycle.ViewModel")
        sb.appendLine("import kotlinx.coroutines.flow.StateFlow")

        for (imp in spec.ipTypeImports) {
            sb.appendLine("import $imp")
        }

        sb.appendLine()
        sb.appendLine("class ${spec.viewModelTypeName} : ViewModel() {")
        sb.appendLine()

        for (sink in spec.sinkInputs) {
            val typeStr = if (sink.isNullable) "${sink.typeName}?" else sink.typeName
            sb.appendLine("    val ${sink.name}: StateFlow<$typeStr> = ${spec.moduleName}State.${sink.name}Flow")
        }

        if (spec.sinkInputs.isNotEmpty() && spec.sourceOutputs.isNotEmpty()) {
            sb.appendLine()
        }

        if (spec.sourceOutputs.isNotEmpty()) {
            val params = spec.sourceOutputs.joinToString(", ") { "${it.name}: ${it.typeName}" }
            sb.appendLine("    fun emit($params) {")
            for (port in spec.sourceOutputs) {
                sb.appendLine("        ${spec.moduleName}State._${port.name}.value = ${port.name}")
            }
            sb.appendLine("    }")
        }

        sb.appendLine()
        sb.appendLine("    fun reset() {")
        sb.appendLine("        ${spec.moduleName}State.reset()")
        sb.appendLine("    }")
        sb.appendLine("}")

        return sb.toString()
    }
}
