/*
 * UIFBPEventGenerator — feature 087 / FR-002.
 *
 * Emits the public `sealed interface {Name}Event` with one nested case per
 * `spec.sourceOutputs` entry, in declared order. Naming convention:
 *   - Valued port: `data class Update<PortName>(val value: T) : {Name}Event`
 *   - `Unit`-typed port: `data object <PortName> : {Name}Event`
 *
 * Empty-events case (FR-008): emits `sealed interface {Name}Event` with no
 * body so the screen's `(state, onEvent) -> Unit` signature stays uniform
 * across modules.
 *
 * License: Apache 2.0
 */

package io.codenode.flowgraphgenerate.generator

import io.codenode.flowgraphgenerate.parser.PortInfo
import io.codenode.flowgraphgenerate.parser.UIFBPSpec

class UIFBPEventGenerator {

    /**
     * Emits `{basePackage}.viewmodel.{Name}Event` per FR-002 + the
     * Update<PortName>/data-object naming convention. See contracts/event-generator.md.
     */
    fun generate(spec: UIFBPSpec): String {
        val sb = StringBuilder()
        val eventName = "${spec.flowGraphPrefix}Event"

        sb.appendLine("/*")
        sb.appendLine(" * $eventName")
        sb.appendLine(" * Generated by CodeNodeIO UIFBPEventGenerator (feature 087 / FR-002)")
        sb.appendLine(" * License: Apache 2.0")
        sb.appendLine(" */")
        sb.appendLine()
        sb.appendLine("package ${spec.packageName}.viewmodel")

        // IP-type imports — only when at least one VALUED source-output port
        // references the type. Unit-typed ports never need an IP-type import.
        val needed = spec.sourceOutputs
            .filter { it.typeName != "Unit" }
            .map { it.typeName }
            .toSet()
        val imports = spec.ipTypeImports.filter { imp -> needed.contains(imp.substringAfterLast('.')) }
        if (imports.isNotEmpty()) {
            sb.appendLine()
            for (imp in imports) {
                sb.appendLine("import $imp")
            }
        }

        sb.appendLine()
        if (spec.sourceOutputs.isEmpty()) {
            // FR-008 — empty hierarchy. Compiler accepts a sealed interface
            // with zero subtypes; the ViewModel's `when (event) { }` is
            // trivially exhaustive.
            sb.appendLine("sealed interface $eventName")
        } else {
            sb.appendLine("sealed interface $eventName {")
            for (port in spec.sourceOutputs) {
                val caseName = pascal(port.name)
                if (port.typeName == "Unit") {
                    sb.appendLine("    data object $caseName : $eventName")
                } else {
                    val typeStr = if (port.isNullable) "${port.typeName}?" else port.typeName
                    sb.appendLine("    data class Update$caseName(val value: $typeStr) : $eventName")
                }
            }
            sb.appendLine("}")
        }

        return sb.toString()
    }

    /** Uppercases the first character of [name] and leaves the rest as-is (no underscore-splitting). */
    private fun pascal(name: String): String =
        if (name.isEmpty()) name
        else name.replaceFirstChar { it.uppercase() }
}
