/*
 * PreviewProviderGeneratorTest - Pins the contract for {Module}PreviewProvider.kt
 * License: Apache 2.0
 */

package io.codenode.flowgraphgenerate.generator

import io.codenode.fbpdsl.model.FlowGraph
import kotlin.test.Test
import kotlin.test.assertTrue

class PreviewProviderGeneratorTest {

    private val generator = PreviewProviderGenerator()
    private val basePackage = "io.codenode.stopwatch"
    private val viewModelPackage = "io.codenode.stopwatch.viewmodel"

    private fun stopWatchFlow(): FlowGraph =
        FlowGraph(
            id = "test-flow",
            name = "StopWatch",
            version = "1.0.0",
            rootNodes = emptyList(),
            connections = emptyList()
        )

    @Test
    fun `emits package under userInterface subpackage`() {
        val source = generator.generate(stopWatchFlow(), basePackage, viewModelPackage)
        assertTrue(source.contains("package io.codenode.stopwatch.userInterface"),
            "PreviewProvider lives in {basePackage}.userInterface so jvmMain consumers " +
                "find it next to the user-facing composable")
    }

    @Test
    fun `emits generator marker comment`() {
        val source = generator.generate(stopWatchFlow(), basePackage, viewModelPackage)
        assertTrue(source.contains("Generated by CodeNodeIO PreviewProviderGenerator"),
            "header must carry the standard generator marker comment")
    }

    @Test
    fun `imports ViewModel from viewmodel subpackage and PreviewRegistry`() {
        val source = generator.generate(stopWatchFlow(), basePackage, viewModelPackage)
        assertTrue(source.contains("import io.codenode.stopwatch.viewmodel.StopWatchViewModel"))
        assertTrue(source.contains("import io.codenode.previewapi.PreviewRegistry"))
    }

    @Test
    fun `emits PreviewProvider object with register function`() {
        val source = generator.generate(stopWatchFlow(), basePackage, viewModelPackage)
        assertTrue(source.contains("object StopWatchPreviewProvider"))
        assertTrue(source.contains("fun register()"))
    }

    @Test
    fun `register function wires composable to PreviewRegistry by module name`() {
        val source = generator.generate(stopWatchFlow(), basePackage, viewModelPackage)
        // The composable name follows the {Module} convention. Modules whose top-level
        // composable diverges (e.g., WeatherForecastUI) can rename after generation.
        assertTrue(source.contains("PreviewRegistry.register(\"StopWatch\")"),
            "must register the composable under the module name")
        assertTrue(source.contains("val vm = viewModel as StopWatchViewModel"),
            "must cast the registry-provided viewModel to the typed ViewModel")
        assertTrue(source.contains("StopWatch(viewModel = vm, modifier = modifier)"),
            "must invoke the {Module}() composable")
    }
}
