/*
 * Filter Node Template
 * Generates code for data filtering nodes
 * License: Apache 2.0
 */

package io.codenode.kotlincompiler.templates

import com.squareup.kotlinpoet.*
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import io.codenode.fbpdsl.model.CodeNode
import io.codenode.fbpdsl.model.CodeNodeType
import io.codenode.kotlincompiler.generator.camelCase
import io.codenode.kotlincompiler.generator.ConfigAwareGenerator

/**
 * Template for generating Filter node components.
 *
 * Filters evaluate a predicate on input data and only emit data
 * that matches the filter criteria.
 *
 * Generated code pattern:
 * ```kotlin
 * class MyFilter {
 *     val input = MutableSharedFlow<Any>()
 *     val output = MutableSharedFlow<Any>()
 *
 *     fun matches(data: Any?): Boolean {
 *         // filter predicate
 *     }
 *
 *     fun start(scope: CoroutineScope) {
 *         scope.launch {
 *             input.collect { data ->
 *                 if (matches(data)) {
 *                     output.emit(data)
 *                 }
 *             }
 *         }
 *     }
 * }
 * ```
 */
class FilterTemplate : NodeTemplate {

    override val nodeType = CodeNodeType.FILTER

    override fun generate(node: CodeNode, className: ClassName): TypeSpec {
        val classBuilder = TypeSpec.classBuilder(className)
            .addKdoc(generateKDoc(node))

        val flowType = ClassName("kotlinx.coroutines.flow", "MutableSharedFlow")
            .parameterizedBy(ANY)

        // Input flow
        val inputName = if (node.inputPorts.isNotEmpty()) {
            node.inputPorts.first().name.camelCase()
        } else {
            "input"
        }
        classBuilder.addProperty(
            PropertySpec.builder("${inputName}Input", flowType)
                .initializer("%T()", ClassName("kotlinx.coroutines.flow", "MutableSharedFlow"))
                .build()
        )

        // Output flow (passed data)
        val outputName = if (node.outputPorts.isNotEmpty()) {
            node.outputPorts.first().name.camelCase()
        } else {
            "output"
        }
        classBuilder.addProperty(
            PropertySpec.builder("${outputName}Output", flowType)
                .initializer("%T()", ClassName("kotlinx.coroutines.flow", "MutableSharedFlow"))
                .build()
        )

        // Rejected flow (optional - filtered out data)
        classBuilder.addProperty(
            PropertySpec.builder("rejectedOutput", flowType)
                .initializer("%T()", ClassName("kotlinx.coroutines.flow", "MutableSharedFlow"))
                .addKdoc("Output for data that doesn't match the filter")
                .build()
        )

        // Add configuration properties
        ConfigAwareGenerator.addConfigurationProperties(classBuilder, node)

        // Add matches function
        classBuilder.addFunction(generateMatchesFunction())

        // Add start function
        classBuilder.addFunction(generateStartFunction(inputName, outputName))

        return classBuilder.build()
    }

    private fun generateKDoc(node: CodeNode): CodeBlock {
        return CodeBlock.builder()
            .add("Filter component: ${node.name}\n")
            .add("\n")
            .add("Filters input data based on a predicate.\n")
            .add("Matching data is emitted to output, non-matching to rejectedOutput.\n")
            .apply {
                node.description?.let { add("\n$it\n") }
            }
            .add("\n")
            .add("@generated by CodeNodeIO KotlinCompiler\n")
            .build()
    }

    private fun generateMatchesFunction(): FunSpec {
        return FunSpec.builder("matches")
            .addModifiers(KModifier.OPEN)
            .addParameter("data", ANY.copy(nullable = true))
            .returns(BOOLEAN)
            .addKdoc("Evaluates the filter predicate.\n")
            .addKdoc("\n")
            .addKdoc("Override this method to implement custom filter logic.\n")
            .addKdoc("\n")
            .addKdoc("@param data The input data to evaluate\n")
            .addKdoc("@return true if data should pass through, false to filter out\n")
            .addCode(CodeBlock.builder()
                .addStatement("// TODO: Implement filter predicate")
                .addStatement("return data != null")
                .build())
            .build()
    }

    private fun generateStartFunction(inputName: String, outputName: String): FunSpec {
        val scopeType = ClassName("kotlinx.coroutines", "CoroutineScope")

        return FunSpec.builder("start")
            .addParameter("scope", scopeType)
            .addKdoc("Starts the filter's processing loop.\n")
            .addCode(CodeBlock.builder()
                .beginControlFlow("scope.launch")
                .beginControlFlow("${inputName}Input.collect { data ->")
                .beginControlFlow("if (matches(data))")
                .addStatement("${outputName}Output.emit(data)")
                .nextControlFlow("else")
                .addStatement("rejectedOutput.emit(data)")
                .endControlFlow()
                .endControlFlow()
                .endControlFlow()
                .build())
            .build()
    }
}
