/*
 * Merger Node Template
 * Generates code for data merging nodes
 * License: Apache 2.0
 */

package io.codenode.kotlincompiler.templates

import com.squareup.kotlinpoet.*
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import io.codenode.fbpdsl.model.CodeNode
import io.codenode.fbpdsl.model.CodeNodeType
import io.codenode.kotlincompiler.generator.camelCase

/**
 * Template for generating Merger node components.
 *
 * Mergers combine data from multiple input ports into a single output.
 * They can merge data as it arrives or wait for all inputs.
 *
 * Generated code pattern:
 * ```kotlin
 * class MyMerger {
 *     val inputA = MutableSharedFlow<Any>()
 *     val inputB = MutableSharedFlow<Any>()
 *     val output = MutableSharedFlow<Any>()
 *
 *     fun merge(inputs: Map<String, Any?>): Any?
 *
 *     fun start(scope: CoroutineScope) {
 *         scope.launch {
 *             merge(inputA, inputB).collect { merged ->
 *                 output.emit(merged)
 *             }
 *         }
 *     }
 * }
 * ```
 */
class MergerTemplate : NodeTemplate {

    override val nodeType = CodeNodeType.MERGER

    override fun generate(node: CodeNode, className: ClassName): TypeSpec {
        val classBuilder = TypeSpec.classBuilder(className)
            .addKdoc(generateKDoc(node))

        val flowType = ClassName("kotlinx.coroutines.flow", "MutableSharedFlow")
            .parameterizedBy(ANY)

        // Input flows for each input port
        val inputNames = if (node.inputPorts.isNotEmpty()) {
            node.inputPorts.map { it.name.camelCase() }
        } else {
            listOf("inputA", "inputB")
        }

        inputNames.forEach { inputName ->
            classBuilder.addProperty(
                PropertySpec.builder("${inputName}Input", flowType)
                    .initializer("%T()", ClassName("kotlinx.coroutines.flow", "MutableSharedFlow"))
                    .build()
            )
        }

        // Output flow
        val outputName = if (node.outputPorts.isNotEmpty()) {
            node.outputPorts.first().name.camelCase()
        } else {
            "output"
        }
        classBuilder.addProperty(
            PropertySpec.builder("${outputName}Output", flowType)
                .initializer("%T()", ClassName("kotlinx.coroutines.flow", "MutableSharedFlow"))
                .build()
        )

        // Add latest values storage
        classBuilder.addProperty(
            PropertySpec.builder(
                "latestValues",
                MUTABLE_MAP.parameterizedBy(STRING, ANY.copy(nullable = true))
            )
                .addModifiers(KModifier.PRIVATE)
                .initializer("mutableMapOf()")
                .build()
        )

        // Add merge function
        classBuilder.addFunction(generateMergeFunction(inputNames))

        // Add start function
        classBuilder.addFunction(generateStartFunction(inputNames, outputName))

        return classBuilder.build()
    }

    private fun generateKDoc(node: CodeNode): CodeBlock {
        return CodeBlock.builder()
            .add("Merger component: ${node.name}\n")
            .add("\n")
            .add("Combines data from multiple inputs into single output.\n")
            .apply {
                node.description?.let { add("\n$it\n") }
            }
            .add("\n")
            .add("@generated by CodeNodeIO KotlinCompiler\n")
            .build()
    }

    private fun generateMergeFunction(inputNames: List<String>): FunSpec {
        val mapType = MAP.parameterizedBy(STRING, ANY.copy(nullable = true))

        return FunSpec.builder("merge")
            .addModifiers(KModifier.OPEN)
            .addParameter("inputs", mapType)
            .returns(ANY.copy(nullable = true))
            .addKdoc("Merges data from multiple inputs.\n")
            .addKdoc("\n")
            .addKdoc("Override this method to implement custom merge logic.\n")
            .addKdoc("By default, returns the inputs as a map.\n")
            .addKdoc("\n")
            .addKdoc("Available inputs: ${inputNames.joinToString(", ")}\n")
            .addKdoc("\n")
            .addKdoc("@param inputs Map of input port names to their latest values\n")
            .addKdoc("@return The merged output value\n")
            .addCode(CodeBlock.builder()
                .addStatement("// TODO: Implement merge logic")
                .addStatement("// Default: return all inputs as a map")
                .addStatement("return inputs")
                .build())
            .build()
    }

    private fun generateStartFunction(inputNames: List<String>, outputName: String): FunSpec {
        val scopeType = ClassName("kotlinx.coroutines", "CoroutineScope")

        return FunSpec.builder("start")
            .addParameter("scope", scopeType)
            .addKdoc("Starts the merger's processing loop.\n")
            .addKdoc("Listens to all inputs and emits merged output when any input arrives.\n")
            .addCode(CodeBlock.builder()
                .apply {
                    // Launch a collector for each input
                    inputNames.forEach { inputName ->
                        beginControlFlow("scope.launch")
                        beginControlFlow("${inputName}Input.collect { data ->")
                        addStatement("latestValues[\"$inputName\"] = data")
                        addStatement("val merged = merge(latestValues.toMap())")
                        addStatement("${outputName}Output.emit(merged)")
                        endControlFlow()
                        endControlFlow()
                        add("\n")
                    }
                }
                .build())
            .build()
    }
}
