/*
 * Transformer Node Template
 * Generates code for data transformation nodes
 * License: Apache 2.0
 */

package io.codenode.kotlincompiler.templates

import com.squareup.kotlinpoet.*
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import io.codenode.fbpdsl.model.CodeNode
import io.codenode.fbpdsl.model.CodeNodeType
import io.codenode.kotlincompiler.generator.camelCase
import io.codenode.kotlincompiler.generator.ComponentGenerator

/**
 * Template for generating Transformer node components.
 *
 * Transformers take input data and produce transformed output data.
 * They have exactly one input and one output port typically.
 *
 * Generated code pattern:
 * ```kotlin
 * class MyTransformer {
 *     val input = MutableSharedFlow<Any>()
 *     val output = MutableSharedFlow<Any>()
 *
 *     suspend fun transform(data: Any?): Any? {
 *         // transformation logic
 *     }
 *
 *     fun start(scope: CoroutineScope) {
 *         scope.launch {
 *             input.collect { data ->
 *                 output.emit(transform(data))
 *             }
 *         }
 *     }
 * }
 * ```
 */
class TransformerTemplate : NodeTemplate {

    override val nodeType = CodeNodeType.TRANSFORMER

    override fun generate(node: CodeNode, className: ClassName): TypeSpec {
        val classBuilder = TypeSpec.classBuilder(className)
            .addKdoc(generateKDoc(node))

        // Add flow properties
        val flowType = ClassName("kotlinx.coroutines.flow", "MutableSharedFlow")
            .parameterizedBy(ANY)

        // Input flow
        val inputName = if (node.inputPorts.isNotEmpty()) {
            node.inputPorts.first().name.camelCase()
        } else {
            "input"
        }
        classBuilder.addProperty(
            PropertySpec.builder("${inputName}Input", flowType)
                .initializer("%T()", ClassName("kotlinx.coroutines.flow", "MutableSharedFlow"))
                .build()
        )

        // Output flow
        val outputName = if (node.outputPorts.isNotEmpty()) {
            node.outputPorts.first().name.camelCase()
        } else {
            "output"
        }
        classBuilder.addProperty(
            PropertySpec.builder("${outputName}Output", flowType)
                .initializer("%T()", ClassName("kotlinx.coroutines.flow", "MutableSharedFlow"))
                .build()
        )

        // Add transform function
        classBuilder.addFunction(generateTransformFunction(inputName))

        // Add start function
        classBuilder.addFunction(generateStartFunction(inputName, outputName))

        return classBuilder.build()
    }

    private fun generateKDoc(node: CodeNode): CodeBlock {
        return CodeBlock.builder()
            .add("Transformer component: ${node.name}\n")
            .add("\n")
            .add("Transforms input data to output format.\n")
            .apply {
                node.description?.let { add("\n$it\n") }
            }
            .add("\n")
            .add("@generated by CodeNodeIO KotlinCompiler\n")
            .build()
    }

    private fun generateTransformFunction(inputName: String): FunSpec {
        return FunSpec.builder("transform")
            .addModifiers(KModifier.SUSPEND, KModifier.OPEN)
            .addParameter("data", ANY.copy(nullable = true))
            .returns(ANY.copy(nullable = true))
            .addKdoc("Transforms input data.\n")
            .addKdoc("\n")
            .addKdoc("Override this method to implement custom transformation logic.\n")
            .addKdoc("\n")
            .addKdoc("@param data The input data to transform\n")
            .addKdoc("@return The transformed data\n")
            .addCode(CodeBlock.builder()
                .addStatement("// TODO: Implement transformation logic")
                .addStatement("return data")
                .build())
            .build()
    }

    private fun generateStartFunction(inputName: String, outputName: String): FunSpec {
        val scopeType = ClassName("kotlinx.coroutines", "CoroutineScope")

        return FunSpec.builder("start")
            .addParameter("scope", scopeType)
            .addKdoc("Starts the transformer's processing loop.\n")
            .addCode(CodeBlock.builder()
                .beginControlFlow("scope.launch")
                .beginControlFlow("${inputName}Input.collect { data ->")
                .addStatement("val result = transform(data)")
                .addStatement("${outputName}Output.emit(result)")
                .endControlFlow()
                .endControlFlow()
                .build())
            .build()
    }
}
