/*
 * Build Script Generator
 * Generates build.gradle.kts files for KMP projects
 * License: Apache 2.0
 */

package io.codenode.kotlincompiler.generator

import io.codenode.fbpdsl.model.FlowGraph

/**
 * Generates Gradle build scripts for Kotlin Multiplatform projects.
 *
 * Creates properly configured build.gradle.kts files that:
 * - Configure KMP plugin with appropriate targets
 * - Add necessary dependencies (coroutines, serialization, etc.)
 * - Set up source sets for common, Android, iOS, and JS code
 * - Include constitution-compliant dependencies only
 */
class BuildScriptGenerator {

    companion object {
        const val KOTLIN_VERSION = "2.1.0"
        const val COROUTINES_VERSION = "1.8.0"
        const val SERIALIZATION_VERSION = "1.6.0"
        const val COMPOSE_VERSION = "1.6.0"
    }

    /**
     * Configuration for target platforms
     */
    data class TargetConfig(
        val android: Boolean = false,
        val ios: Boolean = false,
        val desktop: Boolean = false,
        val js: Boolean = false,
        val wasm: Boolean = false,
        val androidMinSdk: Int = 24,
        val androidTargetSdk: Int = 34,
        val androidCompileSdk: Int = 34,
        val iosDeploymentTarget: String = "14.0"
    )

    /**
     * Generates a complete build.gradle.kts for a KMP project.
     *
     * @param flowGraph The flow graph to generate build script for
     * @param config Target platform configuration
     * @return Generated build.gradle.kts content
     */
    fun generateBuildScript(flowGraph: FlowGraph, config: TargetConfig): String {
        return buildString {
            appendLine(generateHeader(flowGraph))
            appendLine()
            appendLine(generatePlugins(config))
            appendLine()
            appendLine(generateKotlinBlock(config))
            appendLine()
            appendLine(generateAndroidBlockIfNeeded(config))
            appendLine()
            appendLine(generateDependencies())
        }
    }

    /**
     * Generates the settings.gradle.kts content.
     *
     * @param projectName The name of the project
     * @return Generated settings.gradle.kts content
     */
    fun generateSettingsScript(projectName: String): String {
        return buildString {
            appendLine("/*")
            appendLine(" * Settings for $projectName")
            appendLine(" * Generated by CodeNodeIO")
            appendLine(" * License: Apache 2.0")
            appendLine(" */")
            appendLine()
            appendLine("pluginManagement {")
            appendLine("    repositories {")
            appendLine("        google()")
            appendLine("        mavenCentral()")
            appendLine("        gradlePluginPortal()")
            appendLine("    }")
            appendLine("}")
            appendLine()
            appendLine("dependencyResolutionManagement {")
            appendLine("    repositories {")
            appendLine("        google()")
            appendLine("        mavenCentral()")
            appendLine("    }")
            appendLine("}")
            appendLine()
            appendLine("rootProject.name = \"$projectName\"")
        }
    }

    /**
     * Generates the gradle.properties content.
     *
     * @return Generated gradle.properties content
     */
    fun generateGradleProperties(): String {
        return buildString {
            appendLine("# Project-wide Gradle settings")
            appendLine("# Generated by CodeNodeIO")
            appendLine()
            appendLine("# Kotlin")
            appendLine("kotlin.code.style=official")
            appendLine("kotlin.mpp.stability.nowarn=true")
            appendLine()
            appendLine("# Android")
            appendLine("android.useAndroidX=true")
            appendLine("android.nonTransitiveRClass=true")
            appendLine()
            appendLine("# Performance")
            appendLine("org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8")
            appendLine("org.gradle.parallel=true")
            appendLine("org.gradle.caching=true")
            appendLine("org.gradle.configuration-cache=true")
        }
    }

    private fun generateHeader(flowGraph: FlowGraph): String {
        return buildString {
            appendLine("/*")
            appendLine(" * Build script for ${flowGraph.name}")
            appendLine(" * Version: ${flowGraph.version}")
            appendLine(" * Generated by CodeNodeIO")
            appendLine(" * License: Apache 2.0")
            appendLine(" */")
        }
    }

    private fun generatePlugins(config: TargetConfig): String {
        return buildString {
            appendLine("plugins {")
            appendLine("    kotlin(\"multiplatform\") version \"$KOTLIN_VERSION\"")
            appendLine("    kotlin(\"plugin.serialization\") version \"$KOTLIN_VERSION\"")
            if (config.android) {
                appendLine("    id(\"com.android.library\") version \"8.2.0\"")
            }
            if (config.desktop || config.android || config.ios) {
                appendLine("    id(\"org.jetbrains.compose\") version \"$COMPOSE_VERSION\"")
            }
            appendLine("}")
        }
    }

    private fun generateKotlinBlock(config: TargetConfig): String {
        return buildString {
            appendLine("kotlin {")

            // JVM target (always included for common testing)
            appendLine("    jvm {")
            appendLine("        compilations.all {")
            appendLine("            kotlinOptions.jvmTarget = \"17\"")
            appendLine("        }")
            appendLine("    }")

            // Android target
            if (config.android) {
                appendLine()
                appendLine("    androidTarget {")
                appendLine("        compilations.all {")
                appendLine("            kotlinOptions.jvmTarget = \"17\"")
                appendLine("        }")
                appendLine("    }")
            }

            // iOS targets
            if (config.ios) {
                appendLine()
                appendLine("    listOf(")
                appendLine("        iosX64(),")
                appendLine("        iosArm64(),")
                appendLine("        iosSimulatorArm64()")
                appendLine("    ).forEach { iosTarget ->")
                appendLine("        iosTarget.binaries.framework {")
                appendLine("            baseName = \"shared\"")
                appendLine("            isStatic = true")
                appendLine("        }")
                appendLine("    }")
            }

            // JS target
            if (config.js) {
                appendLine()
                appendLine("    js(IR) {")
                appendLine("        browser {")
                appendLine("            commonWebpackConfig {")
                appendLine("                cssSupport {")
                appendLine("                    enabled.set(true)")
                appendLine("                }")
                appendLine("            }")
                appendLine("        }")
                appendLine("        binaries.executable()")
                appendLine("    }")
            }

            // Wasm target
            if (config.wasm) {
                appendLine()
                appendLine("    wasmJs {")
                appendLine("        browser()")
                appendLine("        binaries.executable()")
                appendLine("    }")
            }

            // Source sets
            appendLine()
            appendLine("    sourceSets {")
            appendLine("        val commonMain by getting {")
            appendLine("            dependencies {")
            appendLine("                implementation(\"org.jetbrains.kotlinx:kotlinx-coroutines-core:$COROUTINES_VERSION\")")
            appendLine("                implementation(\"org.jetbrains.kotlinx:kotlinx-serialization-json:$SERIALIZATION_VERSION\")")
            appendLine("            }")
            appendLine("        }")
            appendLine()
            appendLine("        val commonTest by getting {")
            appendLine("            dependencies {")
            appendLine("                implementation(kotlin(\"test\"))")
            appendLine("            }")
            appendLine("        }")

            if (config.android) {
                appendLine()
                appendLine("        val androidMain by getting {")
                appendLine("            dependencies {")
                appendLine("                implementation(\"org.jetbrains.kotlinx:kotlinx-coroutines-android:$COROUTINES_VERSION\")")
                appendLine("            }")
                appendLine("        }")
            }

            if (config.ios) {
                appendLine()
                appendLine("        val iosX64Main by getting")
                appendLine("        val iosArm64Main by getting")
                appendLine("        val iosSimulatorArm64Main by getting")
                appendLine("        val iosMain by creating {")
                appendLine("            dependsOn(commonMain)")
                appendLine("            iosX64Main.dependsOn(this)")
                appendLine("            iosArm64Main.dependsOn(this)")
                appendLine("            iosSimulatorArm64Main.dependsOn(this)")
                appendLine("        }")
            }

            if (config.js) {
                appendLine()
                appendLine("        val jsMain by getting {")
                appendLine("            dependencies {")
                appendLine("                // JS-specific dependencies")
                appendLine("            }")
                appendLine("        }")
            }

            appendLine("    }")
            appendLine("}")
        }
    }

    private fun generateAndroidBlockIfNeeded(config: TargetConfig): String {
        if (!config.android) return ""

        return buildString {
            appendLine("android {")
            appendLine("    namespace = \"io.codenode.generated\"")
            appendLine("    compileSdk = ${config.androidCompileSdk}")
            appendLine()
            appendLine("    defaultConfig {")
            appendLine("        minSdk = ${config.androidMinSdk}")
            appendLine("        targetSdk = ${config.androidTargetSdk}")
            appendLine("    }")
            appendLine()
            appendLine("    compileOptions {")
            appendLine("        sourceCompatibility = JavaVersion.VERSION_17")
            appendLine("        targetCompatibility = JavaVersion.VERSION_17")
            appendLine("    }")
            appendLine("}")
        }
    }

    private fun generateDependencies(): String {
        return buildString {
            appendLine("// Additional dependencies can be added here")
            appendLine("// All dependencies must comply with Apache 2.0 license requirements")
            appendLine("// NO GPL/LGPL/AGPL dependencies allowed per project constitution")
        }
    }

    /**
     * Determines target configuration from FlowGraph target platforms.
     *
     * @param flowGraph The flow graph to analyze
     * @return TargetConfig based on flow graph's target platforms
     */
    fun configFromFlowGraph(flowGraph: FlowGraph): TargetConfig {
        return TargetConfig(
            android = flowGraph.targetsPlatform(FlowGraph.TargetPlatform.KMP_ANDROID),
            ios = flowGraph.targetsPlatform(FlowGraph.TargetPlatform.KMP_IOS),
            desktop = flowGraph.targetsPlatform(FlowGraph.TargetPlatform.KMP_DESKTOP),
            js = flowGraph.targetsPlatform(FlowGraph.TargetPlatform.KMP_WEB),
            wasm = flowGraph.targetsPlatform(FlowGraph.TargetPlatform.KMP_WASM)
        )
    }
}
