/*
 * EntityDisplayGenerator - Generates {Entity}sDisplay.kt sink node stub files
 * License: Apache 2.0
 */

package io.codenode.kotlincompiler.generator

/**
 * Generates a {Entity}sDisplay.kt sink node stub file parameterized by entity name.
 * Follows the UserProfilesDisplay.kt pattern: a sink node with two inputs
 * (entities/result, error) that updates the module's State object.
 */
class EntityDisplayGenerator {

    /**
     * Generates the {Entity}sDisplay.kt sink node stub content.
     *
     * @param spec The entity module specification
     * @return Complete Kotlin source file content
     */
    fun generate(spec: EntityModuleSpec): String {
        val entityName = spec.entityName
        val pluralName = spec.pluralName

        return buildString {
            appendLine("/*")
            appendLine(" * ${pluralName}Display Sink Node")
            appendLine(" * Generated by CodeNodeIO EntityDisplayGenerator")
            appendLine(" * License: Apache 2.0")
            appendLine(" */")
            appendLine()
            appendLine("package ${spec.basePackage}")
            appendLine()
            appendLine("import io.codenode.fbpdsl.model.CodeNodeFactory")
            appendLine()
            appendLine("/**")
            appendLine(" * Creates the ${pluralName}Display sink node.")
            appendLine(" *")
            appendLine(" * This sink node receives result and error values from the ${entityName}Repository")
            appendLine(" * processor and updates the corresponding StateFlows in ${pluralName}State.")
            appendLine(" */")
            appendLine("internal fun create${pluralName}Display() = CodeNodeFactory.createSinkIn2<Any, Any>(")
            appendLine("    name = \"${pluralName}Display\",")
            appendLine("    consume = { result, error ->")
            appendLine("        ${pluralName}State._result.value = result")
            appendLine("        ${pluralName}State._error.value = error")
            appendLine("    }")
            appendLine(")")
        }
    }
}
