/*
 * EntityCUDGenerator - Generates {Entity}CUD.kt source node stub files
 * License: Apache 2.0
 */

package io.codenode.kotlincompiler.generator

/**
 * Generates a {Entity}CUD.kt source node stub file parameterized by entity name.
 * Follows the UserProfileCUD.kt pattern: a source node with three reactive source
 * outputs (save, update, remove) that collect from StateFlows in the module's State object.
 */
class EntityCUDGenerator {

    /**
     * Generates the {Entity}CUD.kt source node stub content.
     *
     * @param spec The entity module specification
     * @return Complete Kotlin source file content
     */
    fun generate(spec: EntityModuleSpec): String {
        val entityName = spec.entityName
        val pluralName = spec.pluralName

        return buildString {
            appendLine("/*")
            appendLine(" * ${entityName}CUD Source Node")
            appendLine(" * Generated by CodeNodeIO EntityCUDGenerator")
            appendLine(" * License: Apache 2.0")
            appendLine(" */")
            appendLine()
            appendLine("package ${spec.basePackage}")
            appendLine()
            appendLine("import io.codenode.fbpdsl.model.CodeNodeFactory")
            appendLine("import io.codenode.fbpdsl.runtime.ProcessResult3")
            appendLine("import kotlinx.coroutines.coroutineScope")
            appendLine("import kotlinx.coroutines.flow.drop")
            appendLine("import kotlinx.coroutines.launch")
            appendLine()
            appendLine("/**")
            appendLine(" * Creates the ${entityName}CUD source node.")
            appendLine(" *")
            appendLine(" * This source node collects from the save, update, and remove StateFlows")
            appendLine(" * in ${pluralName}State and emits them as a ProcessResult3 to downstream processors.")
            appendLine(" */")
            appendLine("internal fun create${entityName}CUD() = CodeNodeFactory.createSourceOut3<Any, Any, Any>(")
            appendLine("    name = \"${entityName}CUD\",")
            appendLine("    generate = { emit ->")
            appendLine("        coroutineScope {")
            appendLine("            launch {")
            appendLine("                ${pluralName}State._save.drop(1).collect { save ->")
            appendLine("                    if (save != null) {")
            appendLine("                        emit(ProcessResult3(save, null, null))")
            appendLine("                        ${pluralName}State._save.value = null")
            appendLine("                    }")
            appendLine("                }")
            appendLine("            }")
            appendLine("            launch {")
            appendLine("                ${pluralName}State._update.drop(1).collect { update ->")
            appendLine("                    if (update != null) {")
            appendLine("                        emit(ProcessResult3(null, update, null))")
            appendLine("                        ${pluralName}State._update.value = null")
            appendLine("                    }")
            appendLine("                }")
            appendLine("            }")
            appendLine("            launch {")
            appendLine("                ${pluralName}State._remove.drop(1).collect { remove ->")
            appendLine("                    if (remove != null) {")
            appendLine("                        emit(ProcessResult3(null, null, remove))")
            appendLine("                        ${pluralName}State._remove.value = null")
            appendLine("                    }")
            appendLine("                }")
            appendLine("            }")
            appendLine("        }")
            appendLine("    }")
            appendLine(")")
        }
    }
}
