/*
 * EntityRepositoryCodeNodeGenerator - Generates {Entity}RepositoryCodeNode.kt implementing CodeNodeDefinition
 * License: Apache 2.0
 */

package io.codenode.kotlincompiler.generator

/**
 * Generates a {Entity}RepositoryCodeNode.kt file implementing CodeNodeDefinition.
 * This is a TRANSFORMER node with 3 typed inputs (IP type) and 2 String outputs
 * (result, error), using anyInput mode with identity tracking.
 *
 * The generated node converts between IP types and persistence entities at the DAO boundary.
 */
class EntityRepositoryCodeNodeGenerator {

    fun generate(spec: EntityModuleSpec): String {
        val entityName = spec.entityName
        val entityNameLower = spec.entityNameLower
        val pluralName = spec.pluralName
        val nodesPackage = "${spec.basePackage}.nodes"
        val ipTypesPackage = spec.ipTypesPackage

        // Determine the first non-id property name for freshness check and display
        val displayProp = spec.properties.firstOrNull()?.name ?: "id"
        // Build default constructor args for initial values
        val defaultArgs = spec.properties.joinToString(", ") { prop ->
            val default = when (prop.kotlinType) {
                "String" -> "\"\""
                "Int" -> "0"
                "Long" -> "0L"
                "Double" -> "0.0"
                "Float" -> "0.0f"
                "Boolean" -> "false"
                else -> "\"\""
            }
            if (prop.isRequired) "${prop.name} = $default" else "${prop.name} = null"
        }

        return buildString {
            appendLine("/*")
            appendLine(" * ${entityName}RepositoryCodeNode - Self-contained processor node for CRUD persistence")
            appendLine(" * Generated by CodeNodeIO EntityRepositoryCodeNodeGenerator")
            appendLine(" * License: Apache 2.0")
            appendLine(" */")
            appendLine()
            appendLine("package $nodesPackage")
            appendLine()
            appendLine("import io.codenode.fbpdsl.model.CodeNodeFactory")
            appendLine("import io.codenode.fbpdsl.runtime.CodeNodeDefinition")
            appendLine("import io.codenode.fbpdsl.model.CodeNodeType")
            appendLine("import io.codenode.fbpdsl.runtime.NodeRuntime")
            appendLine("import io.codenode.fbpdsl.runtime.PortSpec")
            appendLine("import io.codenode.fbpdsl.runtime.ProcessResult2")
            appendLine("import ${spec.persistencePackage}.${entityName}Repository")
            appendLine("import ${spec.basePackage}.${pluralName}Persistence")
            appendLine("import $ipTypesPackage.$entityName")
            appendLine("import ${spec.basePackage}.toEntity")
            appendLine()
            appendLine("/**")
            appendLine(" * Processor node that performs CRUD operations on ${pluralName.lowercase()}.")
            appendLine(" *")
            appendLine(" * Uses In3AnyOut2 pattern (fires on ANY input change). Per-channel identity")
            appendLine(" * tracking prevents stale cached values from re-triggering operations.")
            appendLine(" * Accesses DAO via ${pluralName}Persistence (Koin).")
            appendLine(" */")
            appendLine("object ${entityName}RepositoryCodeNode : CodeNodeDefinition {")
            appendLine("    override val name = \"${entityName}Repository\"")
            appendLine("    override val category = CodeNodeType.TRANSFORMER")
            appendLine("    override val description = \"Performs save, update, and remove operations on ${pluralName.lowercase()}\"")
            appendLine("    override val inputPorts = listOf(")
            appendLine("        PortSpec(\"save\", $entityName::class),")
            appendLine("        PortSpec(\"update\", $entityName::class),")
            appendLine("        PortSpec(\"remove\", $entityName::class)")
            appendLine("    )")
            appendLine("    override val outputPorts = listOf(")
            appendLine("        PortSpec(\"result\", String::class),")
            appendLine("        PortSpec(\"error\", String::class)")
            appendLine("    )")
            appendLine("    override val anyInput = true")
            appendLine()
            appendLine("    override fun createRuntime(name: String): NodeRuntime {")
            appendLine("        var lastSaveRef: $entityName? = null")
            appendLine("        var lastUpdateRef: $entityName? = null")
            appendLine("        var lastRemoveRef: $entityName? = null")
            appendLine()
            appendLine("        return CodeNodeFactory.createIn3AnyOut2Processor<$entityName, $entityName, $entityName, String, String>(")
            appendLine("            name = name,")
            appendLine("            initialValue1 = $entityName($defaultArgs),")
            appendLine("            initialValue2 = $entityName($defaultArgs),")
            appendLine("            initialValue3 = $entityName($defaultArgs),")
            appendLine("            process = { save, update, remove ->")
            appendLine("                try {")
            appendLine("                    val repo = ${entityName}Repository(${pluralName}Persistence.dao)")
            appendLine("                    val isFreshSave = save !== lastSaveRef && save.$displayProp.toString().isNotEmpty()")
            appendLine("                    val isFreshUpdate = update !== lastUpdateRef && update.$displayProp.toString().isNotEmpty()")
            appendLine("                    val isFreshRemove = remove !== lastRemoveRef && remove.$displayProp.toString().isNotEmpty()")
            appendLine()
            appendLine("                    when {")
            appendLine("                        isFreshSave -> {")
            appendLine("                            lastSaveRef = save")
            appendLine("                            repo.save(save.toEntity())")
            appendLine("                            ProcessResult2.first(\"Saved: \${save.$displayProp}\")")
            appendLine("                        }")
            appendLine("                        isFreshUpdate -> {")
            appendLine("                            lastUpdateRef = update")
            appendLine("                            repo.update(update.toEntity())")
            appendLine("                            ProcessResult2.first(\"Updated: \${update.$displayProp}\")")
            appendLine("                        }")
            appendLine("                        isFreshRemove -> {")
            appendLine("                            lastRemoveRef = remove")
            appendLine("                            repo.remove(remove.toEntity())")
            appendLine("                            ProcessResult2.first(\"Removed: \${remove.$displayProp}\")")
            appendLine("                        }")
            appendLine("                        else -> ProcessResult2(null, null)")
            appendLine("                    }")
            appendLine("                } catch (e: Exception) {")
            appendLine("                    ProcessResult2.second(\"Error: \${e.message}\")")
            appendLine("                }")
            appendLine("            }")
            appendLine("        )")
            appendLine("    }")
            appendLine("}")
        }
    }
}
