/*
 * EntityCUDCodeNodeGenerator - Generates {Entity}CUDCodeNode.kt implementing CodeNodeDefinition
 * License: Apache 2.0
 */

package io.codenode.kotlincompiler.generator

/**
 * Generates a {Entity}CUDCodeNode.kt file implementing CodeNodeDefinition.
 * This is a SOURCE node with 3 typed outputs (save, update, remove) that
 * collects from StateFlows and emits ProcessResult3 values.
 *
 * Replaces the legacy EntityCUDGenerator which produced factory functions.
 */
class EntityCUDCodeNodeGenerator {

    fun generate(spec: EntityModuleSpec): String {
        val entityName = spec.entityName
        val pluralName = spec.pluralName
        val nodesPackage = "${spec.basePackage}.nodes"
        val ipTypesPackage = spec.ipTypesPackage

        return buildString {
            appendLine("/*")
            appendLine(" * ${entityName}CUDCodeNode - Self-contained source node for CRUD operations")
            appendLine(" * Generated by CodeNodeIO EntityCUDCodeNodeGenerator")
            appendLine(" * License: Apache 2.0")
            appendLine(" */")
            appendLine()
            appendLine("package $nodesPackage")
            appendLine()
            appendLine("import io.codenode.fbpdsl.model.CodeNodeFactory")
            appendLine("import io.codenode.fbpdsl.runtime.CodeNodeDefinition")
            appendLine("import io.codenode.fbpdsl.model.CodeNodeType")
            appendLine("import io.codenode.fbpdsl.runtime.NodeRuntime")
            appendLine("import io.codenode.fbpdsl.runtime.PortSpec")
            appendLine("import io.codenode.fbpdsl.runtime.ProcessResult3")
            appendLine("import ${spec.basePackage}.${pluralName}State")
            appendLine("import $ipTypesPackage.$entityName")
            appendLine("import kotlinx.coroutines.coroutineScope")
            appendLine("import kotlinx.coroutines.flow.drop")
            appendLine("import kotlinx.coroutines.launch")
            appendLine()
            appendLine("/**")
            appendLine(" * Source node that emits save, update, and remove operations from ${pluralName}State.")
            appendLine(" *")
            appendLine(" * Collects from the _save, _update, and _remove StateFlows independently")
            appendLine(" * (each in its own coroutine). When a non-null value arrives, emits a")
            appendLine(" * selective ProcessResult3 and resets the state to null.")
            appendLine(" */")
            appendLine("object ${entityName}CUDCodeNode : CodeNodeDefinition {")
            appendLine("    override val name = \"${entityName}CUD\"")
            appendLine("    override val category = CodeNodeType.SOURCE")
            appendLine("    override val description = \"Emits save, update, and remove operations for ${pluralName.lowercase()}\"")
            appendLine("    override val inputPorts = emptyList<PortSpec>()")
            appendLine("    override val outputPorts = listOf(")
            appendLine("        PortSpec(\"save\", $entityName::class),")
            appendLine("        PortSpec(\"update\", $entityName::class),")
            appendLine("        PortSpec(\"remove\", $entityName::class)")
            appendLine("    )")
            appendLine()
            appendLine("    override fun createRuntime(name: String): NodeRuntime {")
            appendLine("        return CodeNodeFactory.createSourceOut3<$entityName, $entityName, $entityName>(")
            appendLine("            name = name,")
            appendLine("            generate = { emit ->")
            appendLine("                coroutineScope {")
            appendLine("                    launch {")
            appendLine("                        ${pluralName}State._save.drop(1).collect { save ->")
            appendLine("                            if (save != null) {")
            appendLine("                                emit(ProcessResult3(save, null, null))")
            appendLine("                                ${pluralName}State._save.value = null")
            appendLine("                            }")
            appendLine("                        }")
            appendLine("                    }")
            appendLine("                    launch {")
            appendLine("                        ${pluralName}State._update.drop(1).collect { update ->")
            appendLine("                            if (update != null) {")
            appendLine("                                emit(ProcessResult3(null, update, null))")
            appendLine("                                ${pluralName}State._update.value = null")
            appendLine("                            }")
            appendLine("                        }")
            appendLine("                    }")
            appendLine("                    launch {")
            appendLine("                        ${pluralName}State._remove.drop(1).collect { remove ->")
            appendLine("                            if (remove != null) {")
            appendLine("                                emit(ProcessResult3(null, null, remove))")
            appendLine("                                ${pluralName}State._remove.value = null")
            appendLine("                            }")
            appendLine("                        }")
            appendLine("                    }")
            appendLine("                }")
            appendLine("            }")
            appendLine("        )")
            appendLine("    }")
            appendLine("}")
        }
    }
}
