/*
 * EntityUIGenerator - Generates UI composable files for entity CRUD modules
 * License: Apache 2.0
 */

package io.codenode.kotlincompiler.generator

/**
 * Generates three UI composable files for entity modules:
 * - {Entity}s.kt — main list view with add/update/remove buttons
 * - AddUpdate{Entity}.kt — form dialog for creating or editing an entity
 * - {Entity}Row.kt — single row display in the list
 *
 * Each template maps entity properties to form fields and display columns automatically,
 * following the UserProfiles UI pattern.
 */
class EntityUIGenerator {

    /**
     * Generates the {Entity}s.kt list view composable.
     * Contains a scrollable entity list, add/update/remove buttons,
     * selection state, and remove confirmation dialog.
     */
    fun generateListView(spec: EntityModuleSpec): String {
        val entityName = spec.entityName
        val pluralName = spec.pluralName
        val entityNameLower = spec.entityNameLower
        val pluralNameLower = spec.pluralNameLower

        return buildString {
            appendLine("/*")
            appendLine(" * $pluralName Composable")
            appendLine(" * Generated by CodeNodeIO EntityUIGenerator")
            appendLine(" * License: Apache 2.0")
            appendLine(" */")
            appendLine()
            appendLine("package ${spec.basePackage}.userInterface")
            appendLine()
            appendLine("import androidx.compose.foundation.layout.*")
            appendLine("import androidx.compose.foundation.lazy.LazyColumn")
            appendLine("import androidx.compose.foundation.lazy.items")
            appendLine("import androidx.compose.material3.AlertDialog")
            appendLine("import androidx.compose.material3.Button")
            appendLine("import androidx.compose.material3.Divider")
            appendLine("import androidx.compose.material3.MaterialTheme")
            appendLine("import androidx.compose.material3.Text")
            appendLine("import androidx.compose.material3.TextButton")
            appendLine("import androidx.compose.runtime.*")
            appendLine("import androidx.compose.ui.Alignment")
            appendLine("import androidx.compose.ui.Modifier")
            appendLine("import androidx.compose.ui.unit.dp")
            appendLine("import ${spec.basePackage}.${pluralName}ViewModel")
            appendLine("import ${spec.persistencePackage}.${entityName}Entity")
            appendLine()
            appendLine("@Composable")
            appendLine("fun $pluralName(")
            appendLine("    viewModel: ${pluralName}ViewModel,")
            appendLine("    modifier: Modifier = Modifier")
            appendLine(") {")
            appendLine("    val ${pluralNameLower} by viewModel.${pluralNameLower}.collectAsState()")
            appendLine("    var selectedId by remember { mutableStateOf<Long?>(null) }")
            appendLine("    var showAddForm by remember { mutableStateOf(false) }")
            appendLine("    var showUpdateForm by remember { mutableStateOf(false) }")
            appendLine("    var showRemoveConfirmation by remember { mutableStateOf(false) }")
            appendLine()
            appendLine("    val selectedItem = ${pluralNameLower}.find { it.id == selectedId }")
            appendLine()
            appendLine("    // Clear selection if the selected item was removed externally")
            appendLine("    LaunchedEffect(${pluralNameLower}, selectedId) {")
            appendLine("        if (selectedId != null && selectedItem == null) {")
            appendLine("            selectedId = null")
            appendLine("        }")
            appendLine("    }")
            appendLine()
            appendLine("    if (showAddForm) {")
            appendLine("        AddUpdate${entityName}(")
            appendLine("            existingItem = null,")
            appendLine("            onSave = { item ->")
            appendLine("                viewModel.addEntity(item)")
            appendLine("                showAddForm = false")
            appendLine("            },")
            appendLine("            onCancel = { showAddForm = false },")
            appendLine("            modifier = modifier")
            appendLine("        )")
            appendLine("        return")
            appendLine("    }")
            appendLine()
            appendLine("    if (showUpdateForm && selectedItem != null) {")
            appendLine("        AddUpdate${entityName}(")
            appendLine("            existingItem = selectedItem,")
            appendLine("            onSave = { item ->")
            appendLine("                viewModel.updateEntity(item)")
            appendLine("                showUpdateForm = false")
            appendLine("                selectedId = null")
            appendLine("            },")
            appendLine("            onCancel = { showUpdateForm = false },")
            appendLine("            modifier = modifier")
            appendLine("        )")
            appendLine("        return")
            appendLine("    }")
            appendLine()
            appendLine("    Column(")
            appendLine("        modifier = modifier.fillMaxSize().padding(16.dp)")
            appendLine("    ) {")
            appendLine("        Text(")
            appendLine("            text = \"$pluralName\",")
            appendLine("            style = MaterialTheme.typography.headlineMedium,")
            appendLine("            modifier = Modifier.padding(bottom = 16.dp)")
            appendLine("        )")
            appendLine()
            appendLine("        // Header row")
            appendLine("        ${entityName}HeaderRow()")
            appendLine("        Divider()")
            appendLine()
            appendLine("        // List or empty state")
            appendLine("        Box(modifier = Modifier.weight(1f)) {")
            appendLine("            if (${pluralNameLower}.isEmpty()) {")
            appendLine("                Text(")
            appendLine("                    text = \"No ${pluralNameLower} yet\",")
            appendLine("                    style = MaterialTheme.typography.bodyLarge,")
            appendLine("                    modifier = Modifier.align(Alignment.Center)")
            appendLine("                )")
            appendLine("            } else {")
            appendLine("                LazyColumn(modifier = Modifier.fillMaxSize()) {")
            appendLine("                    items(${pluralNameLower}, key = { it.id }) { item ->")
            appendLine("                        ${entityName}Row(")
            appendLine("                            item = item,")
            appendLine("                            isSelected = item.id == selectedId,")
            appendLine("                            onClick = {")
            appendLine("                                selectedId = if (selectedId == item.id) null else item.id")
            appendLine("                            }")
            appendLine("                        )")
            appendLine("                    }")
            appendLine("                }")
            appendLine("            }")
            appendLine("        }")
            appendLine()
            appendLine("        // Button row")
            appendLine("        Row(")
            appendLine("            modifier = Modifier")
            appendLine("                .fillMaxWidth()")
            appendLine("                .padding(top = 16.dp),")
            appendLine("            horizontalArrangement = Arrangement.spacedBy(8.dp)")
            appendLine("        ) {")
            appendLine("            Button(onClick = { showAddForm = true }) {")
            appendLine("                Text(\"Add\")")
            appendLine("            }")
            appendLine("            Button(")
            appendLine("                onClick = { showUpdateForm = true },")
            appendLine("                enabled = selectedItem != null")
            appendLine("            ) {")
            appendLine("                Text(\"Update\")")
            appendLine("            }")
            appendLine("            Button(")
            appendLine("                onClick = { showRemoveConfirmation = true },")
            appendLine("                enabled = selectedItem != null")
            appendLine("            ) {")
            appendLine("                Text(\"Remove\")")
            appendLine("            }")
            appendLine("        }")
            appendLine()
            appendLine("        if (showRemoveConfirmation && selectedItem != null) {")
            appendLine("            AlertDialog(")
            appendLine("                onDismissRequest = { showRemoveConfirmation = false },")
            appendLine("                title = { Text(\"Remove this item?\") },")
            appendLine("                text = { Text(\"Are you sure you want to remove this ${entityNameLower}?\") },")
            appendLine("                confirmButton = {")
            appendLine("                    TextButton(onClick = {")
            appendLine("                        viewModel.removeEntity(selectedItem)")
            appendLine("                        selectedId = null")
            appendLine("                        showRemoveConfirmation = false")
            appendLine("                    }) {")
            appendLine("                        Text(\"Confirm\")")
            appendLine("                    }")
            appendLine("                },")
            appendLine("                dismissButton = {")
            appendLine("                    TextButton(onClick = { showRemoveConfirmation = false }) {")
            appendLine("                        Text(\"Cancel\")")
            appendLine("                    }")
            appendLine("                }")
            appendLine("            )")
            appendLine("        }")
            appendLine("    }")
            appendLine("}")
            appendLine()

            // Generate HeaderRow composable
            appendLine("@Composable")
            appendLine("private fun ${entityName}HeaderRow() {")
            appendLine("    Row(")
            appendLine("        modifier = Modifier")
            appendLine("            .fillMaxWidth()")
            appendLine("            .padding(horizontal = 16.dp, vertical = 12.dp),")
            appendLine("        horizontalArrangement = Arrangement.SpaceBetween,")
            appendLine("        verticalAlignment = Alignment.CenterVertically")
            appendLine("    ) {")

            for ((index, prop) in spec.properties.withIndex()) {
                val weight = if (index == 0) "\n            modifier = Modifier.weight(1f)" else "\n            modifier = Modifier.weight(1f).padding(horizontal = 8.dp)"
                appendLine("        Text(")
                appendLine("            text = \"${prop.name}\",")
                appendLine("            style = MaterialTheme.typography.labelLarge,$weight")
                appendLine("        )")
            }

            appendLine("    }")
            appendLine("}")
        }
    }

    /**
     * Generates the AddUpdate{Entity}.kt form composable.
     * Maps entity properties to form fields per the property-to-UI mapping table:
     * String → OutlinedTextField, Int/Long/Double/Float → numeric OutlinedTextField,
     * Boolean → Checkbox. Optional properties show "(optional)" in label.
     */
    fun generateFormView(spec: EntityModuleSpec): String {
        val entityName = spec.entityName
        val entityNameLower = spec.entityNameLower

        return buildString {
            appendLine("package ${spec.basePackage}.userInterface")
            appendLine()
            appendLine("import androidx.compose.foundation.layout.*")
            appendLine("import androidx.compose.foundation.text.KeyboardOptions")
            appendLine("import androidx.compose.material3.Button")
            appendLine("import androidx.compose.material3.Checkbox")
            appendLine("import androidx.compose.material3.MaterialTheme")
            appendLine("import androidx.compose.material3.OutlinedTextField")
            appendLine("import androidx.compose.material3.Text")
            appendLine("import androidx.compose.runtime.*")
            appendLine("import androidx.compose.ui.Alignment")
            appendLine("import androidx.compose.ui.Modifier")
            appendLine("import androidx.compose.ui.text.input.KeyboardType")
            appendLine("import androidx.compose.ui.unit.dp")
            appendLine("import ${spec.persistencePackage}.${entityName}Entity")
            appendLine()
            appendLine("@Composable")
            appendLine("fun AddUpdate${entityName}(")
            appendLine("    existingItem: ${entityName}Entity? = null,")
            appendLine("    onSave: (${entityName}Entity) -> Unit,")
            appendLine("    onCancel: () -> Unit,")
            appendLine("    modifier: Modifier = Modifier")
            appendLine(") {")

            // Generate state variables for each property
            for (prop in spec.properties) {
                when (prop.kotlinType) {
                    "Boolean" -> {
                        val default = if (prop.isRequired) "existingItem?.${prop.name} ?: true" else "existingItem?.${prop.name} ?: false"
                        appendLine("    var ${prop.name} by remember { mutableStateOf($default) }")
                    }
                    else -> {
                        val default = "existingItem?.${prop.name}?.toString() ?: \"\""
                        appendLine("    var ${prop.name}Text by remember { mutableStateOf($default) }")
                    }
                }
            }
            appendLine()
            appendLine("    val isUpdate = existingItem != null")
            appendLine()
            appendLine("    Column(")
            appendLine("        modifier = modifier.padding(16.dp),")
            appendLine("        verticalArrangement = Arrangement.spacedBy(12.dp)")
            appendLine("    ) {")
            appendLine("        Text(")
            appendLine("            text = if (isUpdate) \"Update ${entityName}\" else \"Add ${entityName}\",")
            appendLine("            style = MaterialTheme.typography.titleMedium")
            appendLine("        )")
            appendLine()

            // Generate form fields for each property
            for (prop in spec.properties) {
                val optionalLabel = if (!prop.isRequired) " (optional)" else ""
                val label = "${prop.name}${optionalLabel}"

                when (prop.kotlinType) {
                    "Boolean" -> {
                        appendLine("        Row(")
                        appendLine("            verticalAlignment = Alignment.CenterVertically")
                        appendLine("        ) {")
                        appendLine("            Checkbox(")
                        appendLine("                checked = ${prop.name},")
                        appendLine("                onCheckedChange = { ${prop.name} = it }")
                        appendLine("            )")
                        appendLine("            Text(\"${prop.name}\")")
                        appendLine("        }")
                        appendLine()
                    }
                    "String" -> {
                        appendLine("        OutlinedTextField(")
                        appendLine("            value = ${prop.name}Text,")
                        appendLine("            onValueChange = { ${prop.name}Text = it },")
                        appendLine("            label = { Text(\"$label\") },")
                        appendLine("            singleLine = true,")
                        appendLine("            modifier = Modifier.fillMaxWidth()")
                        appendLine("        )")
                        appendLine()
                    }
                    "Int", "Long" -> {
                        appendLine("        OutlinedTextField(")
                        appendLine("            value = ${prop.name}Text,")
                        appendLine("            onValueChange = { newValue ->")
                        appendLine("                if (newValue.isEmpty() || newValue.all { it.isDigit() }) {")
                        appendLine("                    ${prop.name}Text = newValue")
                        appendLine("                }")
                        appendLine("            },")
                        appendLine("            label = { Text(\"$label\") },")
                        appendLine("            singleLine = true,")
                        appendLine("            keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Number),")
                        appendLine("            modifier = Modifier.fillMaxWidth()")
                        appendLine("        )")
                        appendLine()
                    }
                    "Double", "Float" -> {
                        appendLine("        OutlinedTextField(")
                        appendLine("            value = ${prop.name}Text,")
                        appendLine("            onValueChange = { newValue ->")
                        appendLine("                if (newValue.isEmpty() || newValue.toDoubleOrNull() != null) {")
                        appendLine("                    ${prop.name}Text = newValue")
                        appendLine("                }")
                        appendLine("            },")
                        appendLine("            label = { Text(\"$label\") },")
                        appendLine("            singleLine = true,")
                        appendLine("            keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Decimal),")
                        appendLine("            modifier = Modifier.fillMaxWidth()")
                        appendLine("        )")
                        appendLine()
                    }
                    else -> {
                        // Default to text field for unknown types
                        appendLine("        OutlinedTextField(")
                        appendLine("            value = ${prop.name}Text,")
                        appendLine("            onValueChange = { ${prop.name}Text = it },")
                        appendLine("            label = { Text(\"$label\") },")
                        appendLine("            singleLine = true,")
                        appendLine("            modifier = Modifier.fillMaxWidth()")
                        appendLine("        )")
                        appendLine()
                    }
                }
            }

            appendLine("        Row(")
            appendLine("            modifier = Modifier.fillMaxWidth(),")
            appendLine("            horizontalArrangement = Arrangement.spacedBy(8.dp)")
            appendLine("        ) {")
            appendLine("            Button(onClick = onCancel) {")
            appendLine("                Text(\"Cancel\")")
            appendLine("            }")
            appendLine("            Button(")
            appendLine("                onClick = {")

            // Build entity constructor call
            appendLine("                    val item = ${entityName}Entity(")
            appendLine("                        id = existingItem?.id ?: 0,")
            for ((index, prop) in spec.properties.withIndex()) {
                val comma = if (index < spec.properties.size - 1) "," else ""
                when (prop.kotlinType) {
                    "Boolean" -> appendLine("                        ${prop.name} = ${prop.name}$comma")
                    "String" -> {
                        if (prop.isRequired) {
                            appendLine("                        ${prop.name} = ${prop.name}Text.trim()$comma")
                        } else {
                            appendLine("                        ${prop.name} = ${prop.name}Text.trim().ifBlank { null }$comma")
                        }
                    }
                    "Int" -> {
                        if (prop.isRequired) {
                            appendLine("                        ${prop.name} = ${prop.name}Text.toIntOrNull() ?: 0$comma")
                        } else {
                            appendLine("                        ${prop.name} = ${prop.name}Text.toIntOrNull()$comma")
                        }
                    }
                    "Long" -> {
                        if (prop.isRequired) {
                            appendLine("                        ${prop.name} = ${prop.name}Text.toLongOrNull() ?: 0L$comma")
                        } else {
                            appendLine("                        ${prop.name} = ${prop.name}Text.toLongOrNull()$comma")
                        }
                    }
                    "Double" -> {
                        if (prop.isRequired) {
                            appendLine("                        ${prop.name} = ${prop.name}Text.toDoubleOrNull() ?: 0.0$comma")
                        } else {
                            appendLine("                        ${prop.name} = ${prop.name}Text.toDoubleOrNull()$comma")
                        }
                    }
                    "Float" -> {
                        if (prop.isRequired) {
                            appendLine("                        ${prop.name} = ${prop.name}Text.toFloatOrNull() ?: 0.0f$comma")
                        } else {
                            appendLine("                        ${prop.name} = ${prop.name}Text.toFloatOrNull()$comma")
                        }
                    }
                    else -> appendLine("                        ${prop.name} = ${prop.name}Text.trim()$comma")
                }
            }
            appendLine("                    )")
            appendLine("                    onSave(item)")
            appendLine("                }")
            appendLine("            ) {")
            appendLine("                Text(if (isUpdate) \"Update\" else \"Add\")")
            appendLine("            }")
            appendLine("        }")
            appendLine("    }")
            appendLine("}")
        }
    }

    /**
     * Generates the {Entity}Row.kt composable.
     * Displays all entity properties in a single clickable row.
     */
    fun generateRowView(spec: EntityModuleSpec): String {
        val entityName = spec.entityName

        return buildString {
            appendLine("package ${spec.basePackage}.userInterface")
            appendLine()
            appendLine("import androidx.compose.foundation.background")
            appendLine("import androidx.compose.foundation.clickable")
            appendLine("import androidx.compose.foundation.layout.*")
            appendLine("import androidx.compose.material3.MaterialTheme")
            appendLine("import androidx.compose.material3.Text")
            appendLine("import androidx.compose.runtime.Composable")
            appendLine("import androidx.compose.ui.Alignment")
            appendLine("import androidx.compose.ui.Modifier")
            appendLine("import androidx.compose.ui.unit.dp")
            appendLine("import ${spec.persistencePackage}.${entityName}Entity")
            appendLine()
            appendLine("@Composable")
            appendLine("fun ${entityName}Row(")
            appendLine("    item: ${entityName}Entity,")
            appendLine("    isSelected: Boolean,")
            appendLine("    onClick: () -> Unit,")
            appendLine("    modifier: Modifier = Modifier")
            appendLine(") {")
            appendLine("    val backgroundColor = if (isSelected) {")
            appendLine("        MaterialTheme.colorScheme.primaryContainer")
            appendLine("    } else {")
            appendLine("        MaterialTheme.colorScheme.surface")
            appendLine("    }")
            appendLine()
            appendLine("    Row(")
            appendLine("        modifier = modifier")
            appendLine("            .fillMaxWidth()")
            appendLine("            .background(backgroundColor)")
            appendLine("            .clickable { onClick() }")
            appendLine("            .padding(horizontal = 16.dp, vertical = 12.dp),")
            appendLine("        horizontalArrangement = Arrangement.SpaceBetween,")
            appendLine("        verticalAlignment = Alignment.CenterVertically")
            appendLine("    ) {")

            // Display each property value (no labels — HeaderRow provides column names)
            for ((index, prop) in spec.properties.withIndex()) {
                val weight = if (index == 0) "\n            modifier = Modifier.weight(1f)" else "\n            modifier = Modifier.weight(1f).padding(horizontal = 8.dp)"
                when (prop.kotlinType) {
                    "Boolean" -> {
                        appendLine("        Text(")
                        appendLine("            text = if (item.${prop.name}) \"Yes\" else \"No\",")
                        appendLine("            style = MaterialTheme.typography.bodyMedium,$weight")
                        appendLine("        )")
                    }
                    else -> {
                        if (prop.isRequired) {
                            appendLine("        Text(")
                            appendLine("            text = \"\${item.${prop.name}}\",")
                            appendLine("            style = MaterialTheme.typography.bodyMedium,$weight")
                            appendLine("        )")
                        } else {
                            appendLine("        Text(")
                            appendLine("            text = \"\${item.${prop.name} ?: \"\u2014\"}\",")
                            appendLine("            style = MaterialTheme.typography.bodyMedium,$weight")
                            appendLine("        )")
                        }
                    }
                }
            }

            appendLine("    }")
            appendLine("}")
        }
    }
}
