/*
 * RuntimeFlowGenerator
 * Generates {Name}Flow.kt from FlowGraph
 * License: Apache 2.0
 */

package io.codenode.kotlincompiler.generator

import io.codenode.fbpdsl.model.CodeNode
import io.codenode.fbpdsl.model.FlowGraph

/**
 * Generates a {Name}Flow.kt file that directly creates runtime instances
 * via CodeNodeFactory, wires connections, and delegates observable state
 * to {ModuleName}State from the viewModel package.
 *
 * The generated Flow class:
 * - Imports tick vals from the processingLogic package
 * - Imports {ModuleName}State from the viewModel package
 * - Creates runtime instances using CodeNodeFactory.create*() methods
 * - Wraps sink consume blocks to update {ModuleName}State + call user tick
 * - Provides start(scope)/stop()/reset()/wireConnections() methods
 */
class RuntimeFlowGenerator {

    private val observableStateResolver = ObservableStateResolver()
    private val connectionWiringResolver = ConnectionWiringResolver()
    private val runtimeTypeResolver = RuntimeTypeResolver()

    /**
     * Generates the {Name}Flow.kt file content from a FlowGraph.
     *
     * @param flowGraph The flow graph to generate from
     * @param generatedPackage The package name for the generated file
     * @param usecasesPackage The package name for user-written tick stubs
     * @param viewModelPackage The base package where {ModuleName}State object lives
     * @return Generated Kotlin source code
     */
    fun generate(
        flowGraph: FlowGraph,
        generatedPackage: String,
        usecasesPackage: String,
        viewModelPackage: String
    ): String {
        val flowName = flowGraph.name.pascalCase()
        val codeNodes = flowGraph.getAllCodeNodes()
        val observableProps = observableStateResolver.getObservableStateProperties(flowGraph)
        val wiringStatements = connectionWiringResolver.getWiringStatements(flowGraph)

        return buildString {
            generateHeader(flowGraph, flowName)
            generatePackage(generatedPackage)
            generateImports(codeNodes, usecasesPackage, observableProps.isNotEmpty(), viewModelPackage, flowName)
            appendLine()
            generateKDoc(flowGraph, flowName)
            appendLine("class ${flowName}Flow {")
            appendLine()

            if (observableProps.isNotEmpty()) {
                generateObservableState(observableProps, flowName)
            }

            generateRuntimeInstances(codeNodes, observableProps, flowGraph, flowName)
            generateStartMethod(codeNodes)
            generateStopMethod(codeNodes)
            generateResetMethod(flowName, observableProps.isNotEmpty())
            generateWireConnectionsMethod(wiringStatements)

            appendLine("}")
            appendLine()
        }
    }

    private fun StringBuilder.generateHeader(flowGraph: FlowGraph, flowName: String) {
        appendLine("/*")
        appendLine(" * $flowName Flow")
        appendLine(" * Generated by CodeNodeIO RuntimeFlowGenerator")
        appendLine(" * License: Apache 2.0")
        appendLine(" */")
        appendLine()
    }

    private fun StringBuilder.generatePackage(generatedPackage: String) {
        appendLine("package $generatedPackage")
        appendLine()
    }

    private fun StringBuilder.generateImports(
        codeNodes: List<CodeNode>,
        usecasesPackage: String,
        hasObservableState: Boolean,
        viewModelPackage: String,
        flowName: String
    ) {
        // Tick function imports from user stubs (source and sink nodes have no stubs)
        codeNodes.filter { it.inputPorts.isNotEmpty() && it.outputPorts.isNotEmpty() }.forEach { node ->
            appendLine("import $usecasesPackage.${node.name.camelCase()}Tick")
        }
        appendLine()

        // Import {ModuleName}State from viewModel package
        if (hasObservableState) {
            appendLine("import $viewModelPackage.${flowName}State")
        }

        // Import entity stub functions (CUD source, Display sink)
        val cudNode = codeNodes.find { it.configuration["_cudSource"] == "true" }
        val displayNode = codeNodes.find { it.configuration["_display"] == "true" }
        if (cudNode != null) {
            appendLine("import $viewModelPackage.create${cudNode.name.pascalCase()}")
        }
        if (displayNode != null) {
            appendLine("import $viewModelPackage.create${displayNode.name.pascalCase()}")
        }
        if (hasObservableState || cudNode != null || displayNode != null) {
            appendLine()
        }

        // Framework imports
        appendLine("import io.codenode.fbpdsl.model.CodeNodeFactory")
        appendLine("import kotlinx.coroutines.CoroutineScope")
        if (hasObservableState) {
            appendLine("import kotlinx.coroutines.flow.StateFlow")
        }

        // Reactive source imports (only for non-entity source nodes)
        val sourceNodes = codeNodes.filter {
            it.inputPorts.isEmpty() && it.outputPorts.isNotEmpty() &&
            it.configuration["_cudSource"] != "true"
        }
        if (sourceNodes.isNotEmpty() && hasObservableState) {
            val maxOutputs = sourceNodes.maxOf { it.outputPorts.size }
            if (maxOutputs >= 2) {
                appendLine("import kotlinx.coroutines.flow.combine")
            }
            appendLine("import kotlinx.coroutines.flow.drop")
            if (maxOutputs == 2) {
                appendLine("import io.codenode.fbpdsl.runtime.ProcessResult2")
            } else if (maxOutputs >= 3) {
                appendLine("import io.codenode.fbpdsl.runtime.ProcessResult2")
                appendLine("import io.codenode.fbpdsl.runtime.ProcessResult3")
            }
        }
    }

    private fun StringBuilder.generateKDoc(flowGraph: FlowGraph, flowName: String) {
        val codeNodes = flowGraph.getAllCodeNodes()
        appendLine("/**")
        appendLine(" * Flow orchestrator for: ${flowGraph.name}")
        appendLine(" *")
        appendLine(" * Version: ${flowGraph.version}")
        flowGraph.description?.let { desc ->
            appendLine(" * Description: $desc")
        }
        appendLine(" *")
        appendLine(" * Nodes: ${codeNodes.size}")
        appendLine(" * Connections: ${flowGraph.connections.size}")
        appendLine(" *")
        appendLine(" * @generated by CodeNodeIO RuntimeFlowGenerator")
        appendLine(" */")
    }

    private fun StringBuilder.generateObservableState(
        observableProps: List<ObservableProperty>,
        flowName: String
    ) {
        appendLine("    // Observable state delegated from module state")
        observableProps.forEach { prop ->
            val typeStr = if (prop.defaultValue == "null") "${prop.typeName}?" else prop.typeName
            appendLine("    val ${prop.name}Flow: StateFlow<$typeStr> = ${flowName}State.${prop.name}Flow")
        }
        appendLine()
    }

    private fun StringBuilder.generateRuntimeInstances(
        codeNodes: List<CodeNode>,
        observableProps: List<ObservableProperty>,
        flowGraph: FlowGraph,
        flowName: String
    ) {
        appendLine("    // Runtime instances")
        codeNodes.forEach { node ->
            val varName = node.name.camelCase()
            val isCudSource = node.configuration["_cudSource"] == "true"
            val isDisplaySink = node.configuration["_display"] == "true"

            // Entity CUD source and Display sink nodes use stub functions
            if (isCudSource) {
                appendLine("    internal val $varName = create${node.name.pascalCase()}()")
                appendLine()
                return@forEach
            }
            if (isDisplaySink) {
                appendLine("    internal val $varName = create${node.name.pascalCase()}()")
                appendLine()
                return@forEach
            }

            val anyInput = node.configuration["_genericType"]?.contains("any") == true
            val factoryMethod = runtimeTypeResolver.getFactoryMethodName(node, anyInput)
            val typeParams = getFactoryTypeParams(node)
            val tickParamName = runtimeTypeResolver.getTickParamName(node, anyInput)
            val isSink = node.inputPorts.isNotEmpty() && node.outputPorts.isEmpty()
            val isSource = node.inputPorts.isEmpty() && node.outputPorts.isNotEmpty()

            appendLine("    internal val $varName = CodeNodeFactory.$factoryMethod<$typeParams>(")
            appendLine("        name = \"${node.name}\",")

            if (isSource) {
                generateReactiveSourceBlock(node, observableProps, flowName)
            } else if (anyInput && node.inputPorts.size >= 2) {
                generateInitialValues(node)
                if (isSink) {
                    generateSinkConsumeBlock(node, varName, tickParamName, observableProps, flowName)
                } else {
                    appendLine("        $tickParamName = ${varName}Tick")
                }
            } else if (isSink) {
                generateSinkConsumeBlock(node, varName, tickParamName, observableProps, flowName)
            } else {
                appendLine("        $tickParamName = ${varName}Tick")
            }

            appendLine("    )")
            appendLine()
        }
    }

    private fun StringBuilder.generateInitialValues(node: CodeNode) {
        node.inputPorts.forEachIndexed { index, port ->
            val typeName = port.dataType.simpleName ?: "Any"
            val defaultVal = defaultForType(typeName)
            appendLine("        initialValue${index + 1} = $defaultVal,")
        }
    }

    private fun defaultForType(typeName: String): String = when (typeName) {
        "Int" -> "0"
        "Long" -> "0L"
        "Double" -> "0.0"
        "Float" -> "0.0f"
        "String" -> "\"\""
        "Boolean" -> "false"
        "Any" -> "Unit"
        else -> "TODO(\"Provide initial value for $typeName\")"
    }

    private fun StringBuilder.generateSinkConsumeBlock(
        node: CodeNode,
        varName: String,
        tickParamName: String,
        observableProps: List<ObservableProperty>,
        flowName: String
    ) {
        val portNames = node.inputPorts.map { it.name.camelCase() }
        val portNamesStr = portNames.joinToString(", ")

        // Find observable properties for this sink's ports
        val sinkProps = node.inputPorts.map { port ->
            observableProps.find { prop ->
                prop.sourceNodeName == node.name && prop.sourcePortName == port.name
            }
        }

        appendLine("        $tickParamName = { $portNamesStr ->")
        val stateName = "${flowName}State"
        sinkProps.forEachIndexed { index, prop ->
            if (prop != null) {
                appendLine("            $stateName._${prop.name}.value = ${portNames[index]}")
            }
        }
        append("        }")
    }

    private fun StringBuilder.generateReactiveSourceBlock(
        node: CodeNode,
        observableProps: List<ObservableProperty>,
        flowName: String
    ) {
        val stateName = "${flowName}State"
        val sourceProps = node.outputPorts.map { port ->
            observableProps.find { prop ->
                prop.sourceNodeName == node.name && prop.sourcePortName == port.name
            }
        }

        val outputCount = node.outputPorts.size

        when (outputCount) {
            1 -> {
                val prop = sourceProps[0]
                if (prop != null) {
                    appendLine("        generate = { emit ->")
                    appendLine("            $stateName._${prop.name}.drop(1).collect { value ->")
                    appendLine("                emit(value)")
                    appendLine("            }")
                    append("        }")
                } else {
                    appendLine("        generate = { _ -> kotlinx.coroutines.awaitCancellation() }")
                }
            }
            2 -> {
                val prop1 = sourceProps[0]
                val prop2 = sourceProps[1]
                if (prop1 != null && prop2 != null) {
                    appendLine("        generate = { emit ->")
                    appendLine("            combine(")
                    appendLine("                $stateName._${prop1.name},")
                    appendLine("                $stateName._${prop2.name}")
                    appendLine("            ) { ${prop1.name}, ${prop2.name} ->")
                    appendLine("                ProcessResult2.both(${prop1.name}, ${prop2.name})")
                    appendLine("            }.drop(1).collect { result ->")
                    appendLine("                emit(result)")
                    appendLine("            }")
                    append("        }")
                } else {
                    appendLine("        generate = { _ -> kotlinx.coroutines.awaitCancellation() }")
                }
            }
            3 -> {
                val prop1 = sourceProps[0]
                val prop2 = sourceProps[1]
                val prop3 = sourceProps[2]
                if (prop1 != null && prop2 != null && prop3 != null) {
                    appendLine("        generate = { emit ->")
                    appendLine("            combine(")
                    appendLine("                $stateName._${prop1.name},")
                    appendLine("                $stateName._${prop2.name},")
                    appendLine("                $stateName._${prop3.name}")
                    appendLine("            ) { ${prop1.name}, ${prop2.name}, ${prop3.name} ->")
                    appendLine("                ProcessResult3(${prop1.name}, ${prop2.name}, ${prop3.name})")
                    appendLine("            }.drop(1).collect { result ->")
                    appendLine("                emit(result)")
                    appendLine("            }")
                    append("        }")
                } else {
                    appendLine("        generate = { _ -> kotlinx.coroutines.awaitCancellation() }")
                }
            }
            else -> {
                appendLine("        generate = { _ -> kotlinx.coroutines.awaitCancellation() }")
            }
        }
    }

    private fun StringBuilder.generateStartMethod(codeNodes: List<CodeNode>) {
        appendLine("    /**")
        appendLine("     * Starts the flow with the given coroutine scope.")
        appendLine("     */")
        appendLine("    suspend fun start(scope: CoroutineScope) {")

        // Start sources first
        val sources = codeNodes.filter { it.inputPorts.isEmpty() && it.outputPorts.isNotEmpty() }
        sources.forEach { node ->
            appendLine("        ${node.name.camelCase()}.start(scope) {}")
        }

        // Wire connections
        appendLine("        wireConnections()")

        // Start non-sources
        val nonSources = codeNodes.filter { !(it.inputPorts.isEmpty() && it.outputPorts.isNotEmpty()) }
        nonSources.forEach { node ->
            appendLine("        ${node.name.camelCase()}.start(scope) {}")
        }

        appendLine("    }")
        appendLine()
    }

    private fun StringBuilder.generateStopMethod(codeNodes: List<CodeNode>) {
        appendLine("    /**")
        appendLine("     * Stops all runtime instances.")
        appendLine("     */")
        appendLine("    fun stop() {")
        codeNodes.forEach { node ->
            appendLine("        ${node.name.camelCase()}.stop()")
        }
        appendLine("    }")
        appendLine()
    }

    private fun StringBuilder.generateResetMethod(
        flowName: String,
        hasObservableState: Boolean
    ) {
        appendLine("    /**")
        appendLine("     * Resets all observable state.")
        appendLine("     */")
        appendLine("    fun reset() {")
        if (hasObservableState) {
            appendLine("        ${flowName}State.reset()")
        }
        appendLine("    }")
        appendLine()
    }

    /**
     * Gets factory-appropriate type parameters for a node.
     * Filters use a single type param; all others use combined input+output types.
     */
    private fun getFactoryTypeParams(node: CodeNode): String {
        val inputs = node.inputPorts.size
        val outputs = node.outputPorts.size
        if (inputs == 1 && outputs == 1) {
            val inType = node.inputPorts[0].dataType.simpleName ?: "Any"
            val outType = node.outputPorts[0].dataType.simpleName ?: "Any"
            if (inType == outType) return inType
        }
        return runtimeTypeResolver.getTypeParams(node)
    }

    private fun StringBuilder.generateWireConnectionsMethod(wiringStatements: List<WiringStatement>) {
        appendLine("    /**")
        appendLine("     * Wires connections between runtime instances.")
        appendLine("     */")
        appendLine("    private fun wireConnections() {")
        wiringStatements.forEach { stmt ->
            appendLine("        ${stmt.targetVarName}.${stmt.targetChannelProp} = ${stmt.sourceVarName}.${stmt.sourceChannelProp}")
        }
        appendLine("    }")
    }
}
