/*
 * RuntimeControllerAdapterGenerator
 * Generates {Name}ControllerAdapter.kt from FlowGraph
 * License: Apache 2.0
 */

package io.codenode.kotlincompiler.generator

import io.codenode.fbpdsl.model.FlowGraph

/**
 * Generates a {Name}ControllerAdapter.kt file wrapping the Controller
 * and implementing the ControllerInterface.
 *
 * The generated adapter:
 * - Takes {Name}Controller as constructor param
 * - Implements {Name}ControllerInterface
 * - Delegates all StateFlow properties and control methods to the controller
 */
class RuntimeControllerAdapterGenerator {

    private val observableStateResolver = ObservableStateResolver()

    /**
     * Generates the {Name}ControllerAdapter.kt file content from a FlowGraph.
     *
     * @param flowGraph The flow graph to generate from
     * @param generatedPackage The package name for the generated file
     * @return Generated Kotlin source code
     */
    fun generate(flowGraph: FlowGraph, generatedPackage: String): String {
        val flowName = flowGraph.name.pascalCase()
        val observableProps = observableStateResolver.getObservableStateProperties(flowGraph)

        return buildString {
            generateHeader(flowName)
            generatePackage(generatedPackage)
            generateImports()
            appendLine()
            generateKDoc(flowName)
            appendLine("class ${flowName}ControllerAdapter(")
            appendLine("    private val controller: ${flowName}Controller")
            appendLine(") : ${flowName}ControllerInterface {")
            appendLine()

            if (observableProps.isNotEmpty()) {
                generateObservableStateDelegation(observableProps)
            }

            generateExecutionStateDelegation()
            generateMethodDelegations()

            appendLine("}")
            appendLine()
        }
    }

    private fun StringBuilder.generateHeader(flowName: String) {
        appendLine("/*")
        appendLine(" * ${flowName}ControllerAdapter")
        appendLine(" * Generated by CodeNodeIO RuntimeControllerAdapterGenerator")
        appendLine(" * License: Apache 2.0")
        appendLine(" */")
        appendLine()
    }

    private fun StringBuilder.generatePackage(generatedPackage: String) {
        appendLine("package $generatedPackage")
        appendLine()
    }

    private fun StringBuilder.generateImports() {
        appendLine("import io.codenode.fbpdsl.model.ExecutionState")
        appendLine("import io.codenode.fbpdsl.model.FlowGraph")
        appendLine("import kotlinx.coroutines.flow.StateFlow")
    }

    private fun StringBuilder.generateKDoc(flowName: String) {
        appendLine("/**")
        appendLine(" * Adapter that wraps the generated ${flowName}Controller to implement")
        appendLine(" * ${flowName}ControllerInterface.")
        appendLine(" *")
        appendLine(" * @param controller The generated ${flowName}Controller to wrap")
        appendLine(" * @generated by CodeNodeIO RuntimeControllerAdapterGenerator")
        appendLine(" */")
    }

    private fun StringBuilder.generateObservableStateDelegation(observableProps: List<ObservableProperty>) {
        observableProps.forEach { prop ->
            appendLine("    override val ${prop.name}: StateFlow<${prop.typeName}>")
            appendLine("        get() = controller.${prop.name}")
            appendLine()
        }
    }

    private fun StringBuilder.generateExecutionStateDelegation() {
        appendLine("    override val executionState: StateFlow<ExecutionState>")
        appendLine("        get() = controller.executionState")
        appendLine()
    }

    private fun StringBuilder.generateMethodDelegations() {
        appendLine("    override fun start(): FlowGraph = controller.start()")
        appendLine()
        appendLine("    override fun stop(): FlowGraph = controller.stop()")
        appendLine()
        appendLine("    override fun reset(): FlowGraph = controller.reset()")
        appendLine()
        appendLine("    override fun pause(): FlowGraph = controller.pause()")
        appendLine()
        appendLine("    override fun resume(): FlowGraph = controller.resume()")
    }
}
