/*
 * UserInterfaceStubGenerator
 * Generates a Composable stub file for the userInterface/ directory
 * License: Apache 2.0
 */

package io.codenode.kotlincompiler.generator

import io.codenode.fbpdsl.model.FlowGraph

/**
 * Generates a single Composable stub file for the userInterface/ subdirectory
 * of a module. The stub contains a basic @Composable function with a Column
 * and Text placeholder, importing the ViewModel from the generated package.
 *
 * This is a write-once generator: existing files are never overwritten,
 * preserving user-implemented UI code.
 */
class UserInterfaceStubGenerator {

    /**
     * Generates a Composable stub file for the given FlowGraph.
     *
     * @param flowGraph The flow graph to generate from
     * @param uiPackage The userInterface subpackage (e.g., io.codenode.mymodule.userInterface)
     * @param generatedPackage The generated package (for ViewModel import)
     * @return Generated Kotlin source code
     */
    fun generate(flowGraph: FlowGraph, uiPackage: String, generatedPackage: String): String {
        val moduleName = flowGraph.name.pascalCase()

        return buildString {
            appendLine("/*")
            appendLine(" * $moduleName Composable")
            appendLine(" * Generated by CodeNodeIO")
            appendLine(" * License: Apache 2.0")
            appendLine(" */")
            appendLine()
            appendLine("package $uiPackage")
            appendLine()
            appendLine("import androidx.compose.foundation.layout.*")
            appendLine("import androidx.compose.material3.Text")
            appendLine("import androidx.compose.runtime.*")
            appendLine("import androidx.compose.ui.Alignment")
            appendLine("import androidx.compose.ui.Modifier")
            appendLine("import androidx.compose.ui.unit.dp")
            appendLine("import $generatedPackage.${moduleName}ViewModel")
            appendLine()
            appendLine("@Composable")
            appendLine("fun $moduleName(")
            appendLine("    viewModel: ${moduleName}ViewModel,")
            appendLine("    modifier: Modifier = Modifier")
            appendLine(") {")
            appendLine("    // TODO: Implement $moduleName UI")
            appendLine("    Column(")
            appendLine("        modifier = modifier,")
            appendLine("        horizontalAlignment = Alignment.CenterHorizontally")
            appendLine("    ) {")
            appendLine("        Text(\"$moduleName\")")
            appendLine("    }")
            appendLine("}")
        }
    }

    /**
     * Returns the stub file name for a given FlowGraph.
     *
     * @param flowGraph The flow graph
     * @return File name (e.g., "StopWatch.kt")
     */
    fun getStubFileName(flowGraph: FlowGraph): String {
        return "${flowGraph.name.pascalCase()}.kt"
    }
}
