/*
 * UIFBPSaveTypes - Result, options, and report shapes for UIFBPSaveService
 *
 * The service itself is jvmMain (filesystem I/O); these types are commonMain
 * so the contract is KMP-safe and consumable from common test fixtures.
 *
 * License: Apache 2.0
 */

package io.codenode.flowgraphgenerate.save

/**
 * Per-call options for [UIFBPSaveService.save].
 */
data class UIFBPSaveOptions(
    /**
     * If true, removes legacy generator-output locations the post-085 pipeline no longer
     * uses (saved/ duplicates and base-package State/ViewModel files). Default false to
     * protect user-edited files; the TestModule migration explicitly opts in via
     * `quickstart.md` VS-A1.
     */
    val deleteLegacyLocations: Boolean = false,

    /**
     * If true, the service parses an existing `.flow.kt` file and merges the new
     * Source/Sink port shape into it (FR-012). If false, an existing `.flow.kt` is
     * left untouched. Default true.
     */
    val mergeExistingFlowKt: Boolean = true
)

/**
 * Aggregate result of one [UIFBPSaveService.save] call.
 *
 * Per FR-013 this is the single structured surface the GraphEditor's status line and
 * any CI/automation consumer reads to learn what changed.
 */
data class UIFBPSaveResult(
    val success: Boolean,
    val files: List<FileChange> = emptyList(),
    val flowKtMerge: FlowKtMergeReport? = null,
    val warnings: List<String> = emptyList(),
    val errorMessage: String? = null
)

/**
 * Per-file outcome of one save call.
 */
data class FileChange(
    val relativePath: String,
    val kind: FileChangeKind,
    val reason: String? = null
)

enum class FileChangeKind {
    /** Target file did not exist; the service wrote it. */
    CREATED,

    /** Target file existed with the generator marker AND content differed; the service overwrote it. */
    UPDATED,

    /** Target file existed with content matching what would be emitted; the service did NOT write. */
    UNCHANGED,

    /**
     * Target file existed without the `Generated by CodeNodeIO` marker — the service refused to
     * overwrite it (FR-016). The file remains on disk; the user must resolve manually.
     */
    SKIPPED_CONFLICT,

    /** Legacy file at a no-longer-emitted path; the service deleted it (only when [UIFBPSaveOptions.deleteLegacyLocations] is true). */
    DELETED
}

/**
 * Report describing the outcome of `.flow.kt` parse-and-merge (Decision 7 / FR-012).
 *
 * `null` when the service did not process a `.flow.kt` (e.g., neither path nor merge option
 * was supplied to `save(...)`).
 */
data class FlowKtMergeReport(
    val mode: FlowKtMergeMode,
    val portsAdded: List<PortChange> = emptyList(),
    val portsRemoved: List<PortChange> = emptyList(),
    val connectionsDropped: List<DroppedConnection> = emptyList(),
    val userNodesPreserved: Int = 0
)

enum class FlowKtMergeMode {
    /** No `.flow.kt` existed; the service emitted the bootstrap. */
    CREATED,

    /** `.flow.kt` existed and the spec's port shape changed; the service applied a structured merge. */
    UPDATED,

    /** `.flow.kt` existed and the spec's port shape matched its current ports; no write. */
    UNCHANGED,

    /** `.flow.kt` existed but `FlowKtParser` could not parse it; the service left the file untouched. */
    PARSE_FAILED_SKIPPED
}

data class PortChange(
    val nodeName: String,
    val portName: String,
    val typeName: String
)

data class DroppedConnection(
    val from: String,
    val to: String,
    val reason: String
)
