/*
 * Settings for New Graph
 * Generated by CodeNodeIO
 * License: Apache 2.0
 */

pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "New Graph"
