/*
 * GenerationFileWriter - Writes GenerationResult content to disk
 *
 * Feature 085 (universal-runtime collapse) extends this writer to:
 *   - Emit `{Module}Runtime.kt` at the module's base package (top-level)
 *   - Schedule deletion of the eliminated thick-stack trio
 *     ({Module}Controller.kt, {Module}ControllerAdapter.kt, {Module}Flow.kt runtime)
 *     during regeneration, with a marker-comment safety check (FR-013) refusing
 *     to delete files that lack the `Generated by CodeNodeIO` marker.
 *
 * License: Apache 2.0
 */

package io.codenode.flowgraphgenerate.runner

import java.io.File

class GenerationFileWriter {

    /**
     * Maps a generator ID to its on-disk path under the module's base source directory.
     * Each path is rooted in the role-named subdirectory the generator owns.
     */
    private val generatorToPath = mapOf(
        "FlowKtGenerator" to { moduleName: String -> "flow/$moduleName.flow.kt" },
        // Feature 085: replaces flow/${moduleName}Flow.kt + controller/${moduleName}Controller.kt
        // + controller/${moduleName}ControllerAdapter.kt. Lives in controller/ alongside
        // the typed ControllerInterface — the Runtime is the controller-tier factory.
        "ModuleRuntimeGenerator" to { moduleName: String -> "controller/${moduleName}Runtime.kt" },
        "RuntimeControllerInterfaceGenerator" to { moduleName: String -> "controller/${moduleName}ControllerInterface.kt" },
        "RuntimeViewModelGenerator" to { moduleName: String -> "viewmodel/${moduleName}ViewModel.kt" },
        "UserInterfaceStubGenerator" to { moduleName: String -> "userInterface/$moduleName.kt" },
        "EntityCUDGenerator" to { moduleName: String -> "nodes/${moduleName}CUDCodeNode.kt" },
        "EntityRepositoryGenerator" to { moduleName: String -> "nodes/${moduleName}RepositoryCodeNode.kt" },
        "EntityDisplayGenerator" to { moduleName: String -> "nodes/${moduleName}DisplayCodeNode.kt" },
        "EntityPersistenceGenerator" to { moduleName: String -> "nodes/${moduleName}Persistence.kt" },
        "UIFBPStateGenerator" to { moduleName: String -> "viewmodel/${moduleName}State.kt" },
        "UIFBPViewModelGenerator" to { moduleName: String -> "viewmodel/${moduleName}ViewModel.kt" },
        "UIFBPSourceGenerator" to { moduleName: String -> "nodes/${moduleName}SourceCodeNode.kt" },
        "UIFBPSinkGenerator" to { moduleName: String -> "nodes/${moduleName}SinkCodeNode.kt" }
    )

    /**
     * Per-regeneration deletion targets. Each path is relative to the module's base
     * source directory and represents a file the previous generation produced that
     * the universal-runtime collapse no longer emits.
     */
    private val deletionTargets = listOf(
        { moduleName: String -> "controller/${moduleName}Controller.kt" },
        { moduleName: String -> "controller/${moduleName}ControllerAdapter.kt" },
        { moduleName: String -> "flow/${moduleName}Flow.kt" }
    )

    private val generatorMarker = "Generated by CodeNodeIO"

    /**
     * Writes generated files to disk and deletes legacy thick-stack files.
     * Returns the list of paths affected (created/updated and deleted).
     *
     * The optional [report] parameter receives a structured per-file outcome,
     * including [FileChangeKind.SKIPPED_CONFLICT] entries for legacy files that
     * lack the `Generated by CodeNodeIO` marker — those are NOT deleted.
     */
    fun write(
        result: GenerationResult,
        moduleDir: File,
        basePackage: String,
        moduleName: String,
        report: MutableList<FileChange> = mutableListOf()
    ): List<String> {
        val basePackagePath = basePackage.replace(".", "/")
        val baseSrcDir = File(moduleDir, "src/commonMain/kotlin/$basePackagePath")
        val filesAffected = mutableListOf<String>()

        for ((generatorId, content) in result.generatedFiles) {
            val pathMapper = generatorToPath[generatorId]
            if (pathMapper != null) {
                val relativePath = pathMapper(moduleName)
                val targetFile = File(baseSrcDir, relativePath)
                val existed = targetFile.exists()
                targetFile.parentFile?.mkdirs()
                targetFile.writeText(content)
                filesAffected.add(relativePath)
                report.add(
                    FileChange(
                        relativePath = relativePath,
                        kind = if (existed) FileChangeKind.UPDATED else FileChangeKind.CREATED
                    )
                )
            }
        }

        // Feature 085: delete legacy thick-stack files (Controller / Adapter / Flow runtime)
        // with a safety check that refuses to delete files lacking the generator marker.
        for (deletionMapper in deletionTargets) {
            val relativePath = deletionMapper(moduleName)
            val targetFile = File(baseSrcDir, relativePath)
            if (!targetFile.exists()) continue

            if (carriesGeneratorMarker(targetFile)) {
                targetFile.delete()
                filesAffected.add(relativePath)
                report.add(
                    FileChange(
                        relativePath = relativePath,
                        kind = FileChangeKind.DELETED,
                        reason = "Eliminated by feature 085 universal-runtime collapse"
                    )
                )
            } else {
                report.add(
                    FileChange(
                        relativePath = relativePath,
                        kind = FileChangeKind.SKIPPED_CONFLICT,
                        reason = "File lacks the \"$generatorMarker\" marker comment; " +
                            "appears hand-edited. Delete or restore manually before re-running."
                    )
                )
            }
        }

        return filesAffected
    }

    /**
     * Checks whether a file's first ~5 lines contain the standard
     * `Generated by CodeNodeIO` marker comment.
     */
    private fun carriesGeneratorMarker(file: File): Boolean {
        return try {
            file.bufferedReader().use { reader ->
                val head = StringBuilder()
                repeat(8) {
                    val line = reader.readLine() ?: return@use head.toString()
                    head.appendLine(line)
                }
                head.toString()
            }.contains(generatorMarker)
        } catch (_: Exception) {
            false
        }
    }
}

/** A single per-file outcome of a [GenerationFileWriter.write] call. */
data class FileChange(
    val relativePath: String,
    val kind: FileChangeKind,
    val reason: String? = null
)

enum class FileChangeKind {
    CREATED,
    UPDATED,
    UNCHANGED,
    DELETED,
    SKIPPED_CONFLICT
}
