/*
 * ModuleScaffoldingGenerator - Creates KMP module directory structure and Gradle files
 * License: Apache 2.0
 */

package io.codenode.flowgraphgenerate.save

import io.codenode.fbpdsl.model.FlowGraph
import io.codenode.flowgraphgenerate.generator.ModuleGenerator
import java.io.File

data class ScaffoldingResult(
    val moduleDir: File,
    val basePackage: String,
    val flowPackage: String,
    val controllerPackage: String,
    val viewModelPackage: String,
    val userInterfacePackage: String,
    val filesCreated: List<String>
)

class ModuleScaffoldingGenerator(
    private val moduleGenerator: ModuleGenerator = ModuleGenerator()
) {

    fun generate(
        moduleName: String,
        outputDir: File,
        targetPlatforms: List<FlowGraph.TargetPlatform> = emptyList(),
        packagePrefix: String = ModuleSaveService.DEFAULT_PACKAGE_PREFIX,
        isEntityModule: Boolean = false
    ): ScaffoldingResult {
        val basePackage = "$packagePrefix.${moduleName.lowercase()}"
        val flowPackage = "$basePackage.${ModuleSaveService.FLOW_SUBPACKAGE}"
        val controllerPackage = "$basePackage.${ModuleSaveService.CONTROLLER_SUBPACKAGE}"
        val viewModelPackage = "$basePackage.${ModuleSaveService.VIEWMODEL_SUBPACKAGE}"
        val userInterfacePackage = "$basePackage.${ModuleSaveService.USER_INTERFACE_SUBPACKAGE}"

        val moduleDir = File(outputDir, moduleName)
        if (!moduleDir.exists()) {
            moduleDir.mkdirs()
        }

        val filesCreated = mutableListOf<String>()

        createDirectoryStructure(moduleDir, basePackage, targetPlatforms)
        createDirectoryStructure(moduleDir, flowPackage, targetPlatforms)
        createDirectoryStructure(moduleDir, controllerPackage, targetPlatforms)
        createDirectoryStructure(moduleDir, viewModelPackage, targetPlatforms)
        createDirectoryStructure(moduleDir, userInterfacePackage, targetPlatforms)

        val nodesPackage = "$basePackage.nodes"
        createDirectoryStructure(moduleDir, nodesPackage, targetPlatforms)

        val iptypesPackage = "$basePackage.iptypes"
        createDirectoryStructure(moduleDir, iptypesPackage, targetPlatforms)

        val buildGradleFile = File(moduleDir, "build.gradle.kts")
        if (!buildGradleFile.exists()) {
            val flowGraph = FlowGraph(
                id = "scaffold_${moduleName.lowercase()}",
                name = moduleName,
                version = "1.0.0",
                targetPlatforms = targetPlatforms
            )
            buildGradleFile.writeText(
                moduleGenerator.generateBuildGradle(flowGraph, moduleName, isEntityModule)
            )
            filesCreated.add("build.gradle.kts")
        }

        val settingsFile = File(moduleDir, "settings.gradle.kts")
        if (!settingsFile.exists()) {
            settingsFile.writeText(generateSettingsGradle(moduleName))
            filesCreated.add("settings.gradle.kts")
        }

        return ScaffoldingResult(
            moduleDir = moduleDir,
            basePackage = basePackage,
            flowPackage = flowPackage,
            controllerPackage = controllerPackage,
            viewModelPackage = viewModelPackage,
            userInterfacePackage = userInterfacePackage,
            filesCreated = filesCreated
        )
    }

    private fun createDirectoryStructure(
        moduleDir: File,
        packageName: String,
        targetPlatforms: List<FlowGraph.TargetPlatform>
    ) {
        val packagePath = packageName.replace(".", "/")

        File(moduleDir, "src/commonMain/kotlin/$packagePath").mkdirs()
        File(moduleDir, "src/commonTest/kotlin/$packagePath").mkdirs()
        File(moduleDir, "src/jvmMain/kotlin/$packagePath").mkdirs()
        File(moduleDir, "src/jvmTest/kotlin").mkdirs()

        if (targetPlatforms.contains(FlowGraph.TargetPlatform.KMP_ANDROID)) {
            File(moduleDir, "src/androidMain/kotlin/$packagePath").mkdirs()
            File(moduleDir, "src/androidTest/kotlin").mkdirs()
        }

        if (targetPlatforms.contains(FlowGraph.TargetPlatform.KMP_IOS)) {
            File(moduleDir, "src/iosMain/kotlin/$packagePath").mkdirs()
            File(moduleDir, "src/iosTest/kotlin").mkdirs()
        }

        if (targetPlatforms.contains(FlowGraph.TargetPlatform.KMP_WEB)) {
            File(moduleDir, "src/jsMain/kotlin/$packagePath").mkdirs()
            File(moduleDir, "src/jsTest/kotlin").mkdirs()
        }

        if (targetPlatforms.contains(FlowGraph.TargetPlatform.KMP_WASM)) {
            File(moduleDir, "src/wasmJsMain/kotlin/$packagePath").mkdirs()
        }
    }

    private fun generateSettingsGradle(moduleName: String): String {
        return buildString {
            appendLine("/*")
            appendLine(" * Settings for $moduleName")
            appendLine(" * Generated by CodeNodeIO ModuleScaffoldingGenerator")
            appendLine(" * License: Apache 2.0")
            appendLine(" */")
            appendLine()
            appendLine("pluginManagement {")
            appendLine("    repositories {")
            appendLine("        google()")
            appendLine("        mavenCentral()")
            appendLine("        gradlePluginPortal()")
            appendLine("    }")
            appendLine("}")
            appendLine()
            appendLine("dependencyResolutionManagement {")
            appendLine("    repositories {")
            appendLine("        google()")
            appendLine("        mavenCentral()")
            appendLine("    }")
            appendLine("}")
            appendLine()
            appendLine("rootProject.name = \"$moduleName\"")
        }
    }
}
