/*
 * UIFBPSaveResultTest - Pins the structured-result data classes for UIFBPSaveService
 * License: Apache 2.0
 */

package io.codenode.flowgraphgenerate.save

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

class UIFBPSaveResultTest {

    @Test
    fun `FileChangeKind covers all five values`() {
        // Per data-model.md §3 — the five kinds are: CREATED, UPDATED, UNCHANGED,
        // SKIPPED_CONFLICT, DELETED. Each maps onto a distinct branch in
        // UIFBPSaveService's per-file decision tree.
        val kinds = FileChangeKind.entries.toSet()
        assertEquals(5, kinds.size)
        assertTrue(FileChangeKind.CREATED in kinds)
        assertTrue(FileChangeKind.UPDATED in kinds)
        assertTrue(FileChangeKind.UNCHANGED in kinds)
        assertTrue(FileChangeKind.SKIPPED_CONFLICT in kinds)
        assertTrue(FileChangeKind.DELETED in kinds)
    }

    @Test
    fun `FlowKtMergeMode covers all four values`() {
        val modes = FlowKtMergeMode.entries.toSet()
        assertEquals(4, modes.size)
        assertTrue(FlowKtMergeMode.CREATED in modes)
        assertTrue(FlowKtMergeMode.UPDATED in modes)
        assertTrue(FlowKtMergeMode.UNCHANGED in modes)
        assertTrue(FlowKtMergeMode.PARSE_FAILED_SKIPPED in modes)
    }

    @Test
    fun `UIFBPSaveResult defaults to empty collections and null errorMessage`() {
        val r = UIFBPSaveResult(success = true)
        assertTrue(r.files.isEmpty())
        assertTrue(r.warnings.isEmpty())
        assertEquals(null, r.flowKtMerge)
        assertEquals(null, r.errorMessage)
    }

    @Test
    fun `UIFBPSaveOptions defaults are conservative`() {
        // Default options must NOT delete legacy locations (FR-016 spirit) but MUST
        // attempt the .flow.kt merge (FR-012 enables a non-destructive re-save flow).
        val o = UIFBPSaveOptions()
        assertEquals(false, o.deleteLegacyLocations)
        assertEquals(true, o.mergeExistingFlowKt)
    }

    @Test
    fun `FileChange and FlowKtMergeReport carry reason and counts`() {
        val fc = FileChange(
            relativePath = "src/commonMain/kotlin/io/codenode/demo/saved/DemoUIState.kt",
            kind = FileChangeKind.SKIPPED_CONFLICT,
            reason = "missing 'Generated by CodeNodeIO' marker"
        )
        assertEquals(FileChangeKind.SKIPPED_CONFLICT, fc.kind)
        assertEquals("missing 'Generated by CodeNodeIO' marker", fc.reason)

        val report = FlowKtMergeReport(
            mode = FlowKtMergeMode.UPDATED,
            portsAdded = listOf(PortChange("DemoUISource", "c", "Double")),
            portsRemoved = emptyList(),
            connectionsDropped = listOf(
                DroppedConnection("DemoUISource.c", "Logger.in", "port removed by spec change")
            ),
            userNodesPreserved = 2
        )
        assertEquals(1, report.portsAdded.size)
        assertEquals(1, report.connectionsDropped.size)
        assertEquals(2, report.userNodesPreserved)
    }
}
